PaloAltoNetworks/docusaurus-openapi-docs

packages/docusaurus-theme-openapi/src/theme/Tabs/index.js
packages/docusaurus-theme-openapi/src/theme/Tabs/styles.module.css

* Modify Tabs component and styling to render arrows (more than 5 response code tabs) and prevent button clipping.
https://user-images.githubusercontent.com/48506502/157128666-c10187b0-a7ad-4b01-beb8-4ca29eb27a0c.mov

Tabs: Fix Arrow Rendering

---

packages/docusaurus-plugin-openapi/src/markdown/createSchemaDetails.ts
packages/docusaurus-theme-openapi/src/theme/Tabs/index.js
packages/docusaurus-theme-openapi/src/theme/Tabs/styles.module.css

* Use styled `<div/>` for response code tab dots
* Add indentation to nested schema levels

UI Cleanup: Response code tabs & schema indentation

---

packages/docusaurus-plugin-openapi/src/markdown/createParamsDetails.ts
packages/docusaurus-plugin-openapi/src/markdown/createSchemaDetails.ts
packages/docusaurus-plugin-openapi/src/markdown/createStatusCodes.ts
packages/docusaurus-theme-openapi/src/theme/ApiItem/styles.module.css
packages/docusaurus-theme-openapi/src/theme/Tabs/index.js
packages/docusaurus-theme-openapi/src/theme/Tabs/styles.module.css

This PR consists of the following changes: 
- Updated `<summary>` marker styling with +- icons
- Updated Schema indentation
- Adjusting `marginLeft` to utilize `rem` units 
- Conditionally setting `marginLeft` if the `firstBody` contains any `items`
- Removal of Schema `object[]` label 
- Updated Tabs to handle smaller desktop sizes
- Remove set `width` and `padding` to allow tab content to fit naturally
https://user-images.githubusercontent.com/48506502/158272244-19b7faec-2647-4bc7-a0df-b8ab77a49a08.mov
https://user-images.githubusercontent.com/48506502/158272912-7c38d5eb-702b-4b60-868e-4aef93fbe6d0.mov

UI Cleanup: Schema Indentation | Updated Summary Marker | Tabs

---

cypress/integration/test.spec.ts
packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx
packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/styles.module.css
packages/docusaurus-theme-openapi/src/theme/ApiItem/index.tsx
packages/docusaurus-theme-openapi/src/theme/ApiItem/styles.module.css
packages/docusaurus-theme-openapi/src/theme/ApiPage/styles.module.css
packages/docusaurus-theme-openapi/src/theme/Tabs/styles.module.css

- Prevents `<ApiDemoPanel />` shifting below pagination buttons for smaller sized screens
- Adjusted media query for displaying API Sidebar
- Import `<DocPaginator />` component into `<ApiDemoPanel />`
- Set media queries to render `<DocPaginator />` component between mobile/desktop
- Ensure that `<DocPaginator />` renders at the bottom of the page
https://user-images.githubusercontent.com/48506502/158897841-7f4a8245-c9d7-4a11-a04e-e4e712006b58.mov
https://user-images.githubusercontent.com/48506502/158898786-6db64bd8-55e3-4c4a-afae-1b6a8d6194a6.mov

[UI Cleanup]: Fix APIDemoPanel shift 

---

packages/docusaurus-theme-openapi/src/theme/ApiPage/styles.module.css
packages/docusaurus-theme-openapi/src/theme/Tabs/styles.module.css

- Revert to original API sidebar media query to remain consistent with mobile breakpoint (996px) throughout the site
- Optimize Tabs styling for better responsiveness
- Change in flex-direction to column for screen sizes up to 500px
- Added padding-left to container to create space between 'Response' title when the user sizes down the screen
https://user-images.githubusercontent.com/48506502/159074558-fed364ab-0557-427d-8d1e-fcc95081bb5a.mov
https://user-images.githubusercontent.com/48506502/159074913-d467ef74-a185-4a8c-98e7-0145cbc8589d.mov

[UI Cleanup]: Responsiveness tweaks v2 | Tabs | Sidebar 

---

CHANGELOG.md
demo/package.json
lerna.json
packages/create-docusaurus-openapi/package.json
packages/docusaurus-plugin-openapi/package.json
packages/docusaurus-plugin-proxy/package.json
packages/docusaurus-preset-openapi/package.json
packages/docusaurus-template-openapi/package.json
packages/docusaurus-theme-openapi/package.json

- Nohoist `postman-collection` and `postman-code-generators` to support package-level patching.
- Add schema guidelines to improve readability.
- Improve responsiveness.
- Add patch-package to standalone packages ([#29](https://github.com/PaloAltoNetworks/docusaurus-openapi/pull/29))
- Add guidelines to collapsible schemas ([#27](https://github.com/PaloAltoNetworks/docusaurus-openapi/pull/27))
- Merge pull request #26 from PaloAltoNetworks/response-tweaks-v2
- Update tabs css
- Revert to original ApiPage media query
- Responsiveness tweaks ([#25](https://github.com/PaloAltoNetworks/docusaurus-openapi/pull/25))
- Manually bump to 17.0.3 ([#24](https://github.com/PaloAltoNetworks/docusaurus-openapi/pull/24))
- Merge pull request #23 …

Prepare release v17.0.4

---

packages/docusaurus-plugin-openapi/package.json
packages/docusaurus-plugin-openapi/src/markdown/createParamsDetails.ts
packages/docusaurus-plugin-openapi/src/markdown/createSchemaDetails.ts
packages/docusaurus-plugin-openapi/src/markdown/index.ts
packages/docusaurus-theme-openapi/package.json
packages/docusaurus-theme-openapi/src/theme/ApiItem/styles.module.css
packages/docusaurus-theme-openapi/src/theme/ParamsItem/index.js
packages/docusaurus-theme-openapi/src/theme/ParamsItem/styles.module.css
packages/docusaurus-theme-openapi/src/theme/SchemaItem/index.js
packages/docusaurus-theme-openapi/src/theme/SchemaItem/styles.module.css
yarn.lock

In efforts to reduce `.mdx` file size by removing duplicated HTML and inline styles. The approach is to encapsulate JSX and any necessary styles into new Theme components, then simply importing them into `.mdx` files. This PR contains a small example (Request Params) as a POC, but a similar approach can potentially be extended further for other components i.e. Request Body, Response Schema, etc.
- Note: Added external library `react-markdown` to handle rendering of Markdown syntax in new theme components
- ~~Collapsible schema functionality~~
- ~~Markdown support for schema description~~

[Optimization]: POC - Create new Theme Components

---

packages/docusaurus-plugin-openapi/package.json
packages/docusaurus-plugin-openapi/src/markdown/createSchemaDetails.ts
yarn.lock

Attempts to add improved support for nested `allOf` schemas by leveraging an external library named `json-schema-merge-allof` to handle resolving and merging nested schemas.
Previous implementation did not handle nested `$refs` in `allOf` schema types.

Improvements/fixes to `allOf` schema support

---

packages/docusaurus-theme-openapi/src/markdown/createDescription.ts
packages/docusaurus-theme-openapi/src/markdown/schema.ts
packages/docusaurus-theme-openapi/src/markdown/utils.ts
packages/docusaurus-theme-openapi/src/theme/ParamsItem/index.js
packages/docusaurus-theme-openapi/src/theme/SchemaItem/index.js
packages/docusaurus-theme-openapi/src/types.ts

Fix warnings when importing `guard()` into `SchemaItem` and `ParamsItem`. 
- The following TS modules and types were copied over from `plugin-openapi` to `theme-openapi`
- `createDescription()`
- `guard()`
- `getQualifierMessage()`
- `getSchemaName()`
- `SchemaObject` type

[Hotfix]: Babel-loader import warnings

---

packages/docusaurus-plugin-openapi/src/docs/docs.ts
packages/docusaurus-plugin-openapi/src/index.ts
packages/docusaurus-plugin-openapi/src/openapi/openapi.ts

Adds prev/next button support for `beforeApiDocs` items.
Improves navigation.

[Experimental] Enable prev/next for beforeApiDocs items

---

packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/VSCode/index.tsx
packages/docusaurus-theme-openapi/src/theme/ApiItem/styles.module.css

- Remove `useMonaco()` hook and revert to original import of `Monaco` type. CORS issue was caused by empty string values being passed into the editor. _Issue resolved in #48_
- Add `--openapi-required` variable to style `required` schema fields
Using the `useMonaco()` hook alongside with `Editor` caused a duplicate module warning in the browser console.

[Cleanup]: Remove useMonaco hook

---

packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/VSCode/index.tsx
packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx
packages/docusaurus-theme-openapi/src/theme/ApiItem/index.tsx
packages/docusaurus-theme-openapi/src/theme/ApiItem/styles.module.css

Introduces fix for #66. Additionally, it attempts to remedy the issue preventing `lastUpdatedAt` and `lastUpdatedBy` from rendering as expected for API docs.
Ended up refactoring `ApiItem` using current `DocItem` as a base. This effectively maintains compatibility with `DocItem` while conditionally rendering the `ApiDemoPanel` and adjusting column widths as necessary. The one caveat is that a future Docusaurus release could introduce breaking changes or new features which could prompt us to refactor `ApiItem`.

Fix paginator issue #66

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchemaDetails.ts

This PR addresses the following issue when generating OpenAPI Docs via the CLI: 
`TypeError: Cannot read properties of undefined (reading 'schema')`
In some cases, OAS files containing `content: {}` within their `responses` property were not being handled properly. To safeguard against this issue, an additional check was added within `createSchemaDetails` to check against `body` and `body.content` emptiness.
https://user-images.githubusercontent.com/48506502/168396773-9a8a5fba-1086-4e0a-b9b5-efdce14f1fe3.mov

[Bug]: TypeError: Cannot read properties of undefined (reading 'schema')

---

demo/src/css/custom.css
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/styles.module.css

Adds missing `--openapi-code-<color>` styles used for syntax highlighting in code samples.
Improves readability of code samples and removes need to specify them in `custom.css`. 
Tested in workspace.
See build preview.

[Bug] Add missing openapi code colors

---

.github/workflows/canary-release.yml

Adds `yarn build-packages` before publishing canary release.
Previous workflow run wasn't compiling typescript resulting in a non-usable package.

Add build-packages to steps

---

packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts

Cleaned up the logic/behavior and usage of `categoryLinkSource` option when grouping paths by tag. 
New expected behavior is as follows:
`categoryLinkSource`: undefined
Multi or single spec? single
Expected result:  Category link configs should be `generated-index` with no description. The "Introduction" doc should be the first item in the sidebar and NOT contain `DocCardList` in the footer.
`categoryLinkSource`: "tag"
Multi or single spec? single
Expected result:  Category link configs should be `generated-index` with description(s) set to tag description(s). The "Introduction" doc should be the first item in the sidebar and NOT contain `DocCardList` in the footer.
`categoryLinkSource`: "info"
Multi or single spec? multi (micro-specs)
Expected result:  Category link configs should link …

[Bug] Refactor categoryLinkSource option and usage

---

packages/docusaurus-plugin-openapi-docs/src/openapi/createExample.ts

Adds try/catch to `createExample` to avoid the following error when schemas cannot be converted to samples:
```bash
TypeError: Cannot read properties of undefined (reading 'default')
```
Part of a larger effort to improve exception handling and allowing generation to continue on failures. See #111 for details.
Tested using a slightly cleaned up PAN-OS REST API spec (10.0).

[Bug] Add try/catch to createExample to prevent TypeError 

---

demo/docs/petstore/swagger-petstore-yaml.info.mdx
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
packages/docusaurus-theme-openapi-docs/src/types.ts

This PR consists of added support for rendering `securitySchemes` within `*.info.mdx` docs. Info docs now contain an "Authentication" section, which renders information regarding Security Schemes specific to an API. For API's that contain multiple `securitySchemes`, users can navigate through different tabs of Security Scheme types. In addition, users can click on a Security Scheme from an OpenAPI Doc page to navigate to the newly added "Authentication" section.
Although we currently have a component to render Authorization related items (`<SecuritySchemes />`) , there are a few missing ingredients in providing more information about a particular Security Scheme. 
- Tested with CSPM API (grouped paths by tags)
- Tested with Expander API (each file treated as a single spec) …

[Experimental] Info Docs: Added Authentication section with support for Security Schemes

---

packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

Now that we're using ReDoc to load and parse we can also support loading specs from URL.
Cause why not?
I tested using https://petstore.swagger.io/v2/swagger.json as `specPath` and then switching back to `petstore.yaml`. Seems to work ok and also up-converted the URL spec from 2.0 to 3.0.
```bash
$ docusaurus gen-api-docs petstore
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Successfully created "docs/petstore/sidebar.js"
Successfully created "docs/petstore/pet.tag.mdx"
Successfully created "docs/petstore/store.tag.mdx"
Successfully created "docs/petstore/user.tag.mdx"
Successfully created "docs/petstore/swagger-petstore.info.mdx"
Successfully created "docs/petstore/uploads-an-image.api.mdx"
Successfully created "docs/petstore/add-a-new-pet-to-the-store.api.mdx" …
```

[Enhancement] Add support for URL specPath

---

README.md
demo/docs/intro.mdx
demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/README.md
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.test.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndBundleSpec.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
yarn.lock

> Note: This PR also renames `docPluginId` to `docsPluginId` to be consistent with Docusaurus
> Note: This PR also introduces a fix for ensuring unique category link slugs when using `groupPathsBy` tag on versioned docs.
Re-inroduces the `json-schema-ref-parser` utility to help handle `$ref` usage that falls outside of the OpenAPI specification. For example, `$ref`s that are used inside descriptions, such as with the CWPP specification.
The following variable was added to `openapi.ts`:
```javascript
// TODO: determine if this should be an API option
// Forces the json-schema-ref-parser
const parseJsonRefs = true;
```
Basically, the behavior is for it to be forced "on" for now. We can make this an API or Plugin option in the future if it makes sense.
Also implemented some basic error …

[Bug] Re-introduce json-schema-ref-parser

---

packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndBundleSpec.ts

Increases dereference timeout from 5 to 15 seconds to allow more time to fetch remote `$ref` pointers, i.e. using http/https.

[Enhancement] Increase dereference timeout

---

packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

This PR addresses #158.
Failure to evaluate `basePath` before defining intro/info and category link doc IDs resulted in a broken sidebar. 
Tested using the Ninja One API spec and config provided in #158.

[Bug] Check for basePath before defining intro and category link doc ids

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts

This PR introduces support for rendering Response Headers, should they exist within an OAS file. The following `header` object properties are supported: 
- `description`
- `schema.type`
- `example` (if provided)
Related to #170 
Tested with `ATP` and `TP` API 

[FR] Add support for Response Headers

---

demo/docs/cos/sidebar.js
demo/docs/petstore/login-user.api.mdx
demo/docs/petstore_versioned/login-user.api.mdx
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts

Remove unnecessary slugs and introduce basePath to necessary slugs
We were using the same basePath for all slugs, meaning that shared id's could result in multiple specs being mapped to the same category-index when they were in separate outputDir's. 
We were also adding slugs to pages that didn't need them e.g. info pages. 
Confirmed links were working correctly in sidebar.js files. Mostly used in generated-index pages which are based on the slug fed, so shouldn't be an issue. 

[Bug] Use basePath in place of slug to avoid duplicate routes

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

This PR introduces the following changes:
1. Fix `createPostmanCollection` method where a copy of `openapiData` is generated
2. Add `groupId` to `Tabs` component for Authentication section in generated `*.info.mdx` file
1. The motivation is to fix the problem when some paths can have their own server object. For example:
```yaml
openapi: 3.0.3
info:
title: Burger Example
version: 1.0.0
description: Sample description.
servers:
- url: https://api.example.com/v1
paths:
/user:
get:
servers:
- url: https://users.example.com/v1
responses:
200:
description: OK
/flavors:
get:
responses:
200:
description: OK
```
The previous realization with `Object.assign` does not copy nested objects, and the next operation with deleting 'servers' attributes removes them into the parent object too.
2. Fix …

[Bug] Fix createPostmanCollection method where a copy of openapiData is generated

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ResponseSamples/index.js
packages/docusaurus-theme-openapi-docs/src/theme/ResponseSamples/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css

This PR introduces added support for response status code examples. Users will now be able to toggle between the Response Schema and any provided examples via `SchemaTabs`.
- Code Sample (`CodeBlock` component)
- Ability to copy or wrap code text for better readability (`CodeBlock` component)
- Status codes containing multiple examples can be selected through tabs (`SchemaTabs` component)
See #119 
So far tested with IoT API, which contains single status code examples and multiple status code examples. Will do further testing on other product API's that contain status code examples.
**Response Status Code examples provided**
https://user-images.githubusercontent.com/48506502/182264634-0fe428ab-1b9f-4ce4-820a-f08e32315dc8.mov
**Response Status Code examples not provided**
- New feature …

[FR] Support for response status code examples 

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

See issue #199 for details/background.
When grouping by tags, the categories should be sorted alphabetically to allow readers to find what they're looking for more easily.
Tested with Petstore, COS and Unleash API.
n/a

[Enhancement] Apply sorting to tags/sidebar categories

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

This change is a regression bug introduced while addressing #199. Essentially, matching operation tag to global tag was failing when `x-displayName` was present. This change eliminates that possibility by avoiding resolving `x-displayName` until immediately before the category label is assigned.
Regression bug fix.
Tested with both Petstore and the sample Unleash API spec.
n/a

[Bug] Ensure operation tags match global tags before building sidebar

---

demo/docs/petstore/login-user.api.mdx
demo/docs/petstore/place-order.api.mdx
demo/docs/petstore_versioned/1.0.0/login-user.api.mdx
demo/docs/petstore_versioned/1.0.0/place-order.api.mdx
demo/docs/petstore_versioned/login-user.api.mdx
demo/docs/petstore_versioned/place-order.api.mdx
packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts

See issue #205 for details background. The TL;DR is that OpenAPI supports either `example` or `examples` under responses. This PR introduces support for a single `example`.
> Note: this PR also conditionally renders `responseHeaders` depending on if examples are present
n/a
Tested with Code API, Shopping API and Petstore.

[Enhancement] Add support for single response example

---

packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js

Uses `react-markdown` components feature to render `SchemaItem` and `ParamsItem` code fences with Docusaurus `CodeBlock` component.
Keeps consistency with Docusaurus code blocks including the theme, and copy and text wrap buttons.
Tested with Threat API, PANOS API, Petstore.
See deploy preview.

[Enhancement] Use CodeBlock to render code fences

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts

There is a typo in the markdown generator code that is pulling in a `TabTtem` rather than a `TabItem` as expected.

Fix typo TabTtem -> TabItem

---

README.md

Readme syntax fix.
Error in readme config syntax.
- Documentation only

Fix missing array opening bracket.

---

demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/index.ts

See #243 and #231  for background.
This approach differs from #243 in that it does not introduce `parseAsync` for performing commands against all plugin instances and configs. Instead, it adds support for a new option, `-p` or `--plugin-id`, which can be used to specify which plugin config to run the command against.
Example usage:
```bash
Usage: docusaurus gen-api-docs <id>
Generates OpenAPI docs in MDX file format and sidebar.js (if enabled).
Options:
-p, --plugin-id <plugin>  OpenAPI docs plugin ID
-h, --help                display help for command
```
* When *no* `-p` or `--plugin-id` option is passed and more than 1 plugin instance exists the command will return an error indicating the plugin ID is required.
* When a `-p` or `--plugin-id` option is passed the command will be executed …

[Experimental] Adds multi-instance support to plugin CLI

---

packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css

Currently, the `<SchemaTabs />` component displays an incorrect render of arrows and displays an overflow when there are multiple example tabs present.
Arrows should be rendered on both left and right side of the tabs and there should be no overflow issues. The expected behavior is similar to `<ApiTabs />`.
Tested with SASE (Tennacy Service Group), which contained multiple example tabs. Ensured that the arrows were present on both left and right sides of the example tabs, as opposed to above and below. Also tested for responsiveness to ensure there weren't any overflow issues.
https://user-images.githubusercontent.com/48506502/189026872-33aceaab-4571-4527-88d7-759591fbef0a.mov

[UI] Fix Schema Tabs arrow render

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormTextInput/index.tsx

Adds tooltips to input fields for handling placeholders that extend beyond the visible width.

[Enhancement] Split placeholder by newline and add title for tooltip

---

demo/docusaurus.config.js

Adds the docusaurus version to the footer of the built demo site.
Useful in development when testing against differing versions of Docusaurus and in PR preview builds.
Tested locally. No adverse behaviour.

Add Docusaurus version to demo footer.

---

packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js

Extends support for both items and non-items params for rendering default value.

[Bug] Handle both items and non-items schemas in renderDefaultValue

---

packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts

Not all discriminators use the `mapping` property to map which ref pointers to apply the discriminator to. This change checks to see if `mapping` exists before attempting to resolve ref pointers. Previously, this was resulting in a `TypeError` for specifications that use `discriminator` with no `mapping`.

[Bug] Check for mapping object before attempting to resolve discriminators

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

See #267 for background
All operations are required to have either an `operationId` or a `summary` defined, as they are used to generate the filename for the MDX output.
Tested with Burgers API.
```bash
$ docusaurus gen-api-docs burgers
Successfully created "docs/food/burgers/burger-example.info.mdx"
Failed to write "docs/food/burgers/.api.mdx" Error: Operation must have summary or operationId defined
```

[Bug] Throw exception when operationId and summary not defined

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

This PR introduces a change to how `docPath` is derived when `--plugin-id` is specified via the CLI.
Prior to this change, the `docPath` was not resolving properly when the `--plugin-id` option was passed via the CLI. This occurred because the `docPath` was resolving based on the first OpenAPI plugin instance and did not factor in the specified `--plugin-id` value, resulting in a mismatch.
Tested using a multi-instance and single-instance Petstore API to ensure no regressions bugs were introduced.

[Bug] Ensure correct docPath is resolved when pluginId is passed

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css

This PR introduces the following changes to our current `<SchemaTabs />` and `<ResponseTabs />` styles: 
- Added background color for both hover and active states: `--ifm-color-emphasis-100`
- Decreased opacity for non-active tabs 
In effort to increase contrast between active/non-active tabs, while maintaining readability for the end-user. In cases where there are only 2 available tabs, there may be a slight confusion in determining which tab is selected.

[Enhancement] Increase contrast between active/non-active Schema/Response Tabs

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

See #291 for background
This solution merges operation params with common params. Operation params will take precedence when a common param with the same `name` exists.
Common parameters are defined in the OpenAPI specification and should be supported.
See deploy preview (Petstore API)

[Enhancement] Add support for common params

---

demo/examples/petstore.yaml
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Body/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js

See #280 for background.
Renders `requestBody` example(s) inside `SchemaTabs`. Uses `lazy` option to prevent all tab items from rendering on first load - instead, the code sample should update each time an example tab is selected.
If you're looking to test use this: https://gist.github.com/biggates/4955d608379a8b1b3224e815c7dd0dc9

[Enhancement] Add support for request examples

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/styles.module.css

Addresses issue with mobile devices losing all formatting (white space) for json syntax highlighting in `Body`.

[Bug] Switch from nowrap to pre

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createDescription.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts
packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
yarn.lock

See #299  for background.
This PR implements selective replace for `<` and `>` characters in order to preserve support for inline HTML. Previously, `lodash` `escape()` was being used to HTML-encode all special characters, which broke inline-HTML.
Renders titles and descriptions as intended, including HTML.
Tested with Petstore and IOT APIs but more testing will be welcomed to ensure no regression bugs are introduced.
Additional testing with Threat Prevention API.
> Note: during IOT testing I found that there were improperly formatted tags, like `<b> <b/>` which I needed to fix in order to successfully build. Previously, these issues were being masked.

[Bug] Implement selective escape for sanitizing titles and descriptions

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

Disables warning message when loading specs from directory path.

Disable warning when loading specs from directory

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

See #295 for background.
Issue stemmed from a discrepancy between the ways "preset-classic" can be defined in `docusaurus.config.js`.
```
presets: [
[
"classic",
```
vs
```
presets: [
[
"@docusaurus/preset-classic",
```
The difference went unnoticed which led to a broken `infoPath`.

[Bug] Use endsWith to match docsPluginId to preset

---

demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createDownload.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Export/index.tsx
yarn.lock

See #113 for background
Usage:
Add the `downloadUrl` option to your OpenAPI plugin config.
```
petstore: {
specPath: "examples/petstore.yaml",
outputDir: "docs/petstore",
sidebarOptions: {
groupPathsBy: "tag",
categoryLinkSource: "tag",
},
downloadUrl:
"https://raw.githubusercontent.com/PaloAltoNetworks/docusaurus-openapi-docs/main/demo/examples/petstore.yaml",
},
```
TODO:
Findings:
* Requires the spec to have an `info` section
* GitHub seems to respond with proper CORS headers

[Enhancement] Introduce support for downloading OpenAPI spec

---

packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts

Current regex replaces occurrences of `>` or `<` when followed by `=`, such as `>=` or `<=`. This change updates regular expressions to ignore those occurrences.
Example:

[Bug] Extend regex to ignore <= and >=

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx

Wraps API doc items in `BrowserOnly` to prevent SSR issues while conditionally pre-rendering non-API docs.
(Notice the TOC doesn't render on first load)
https://user-images.githubusercontent.com/9343811/198031260-6d5cd9de-225f-4252-8647-0fe5061ea707.mov
> Note: this has the side-effect of making API docs CSR only, which could negatively impact SEO. Will continue to work on ways to SSR + hydrate API docs.

[Bug] Wrap API docs in BrowserOnly

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/persistanceMiddleware.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/store.ts

Re-introduces support for SSR of API docs. Effect is that only the first column under `ApiItem` will be SSR, meaning the `ApiDemoPanel` will continue to be CSR.
Ability to SSR API docs will help improve SEO scores and provide greater support for third-party search engines.
Test with deploy preview. Disable javascript to test SSR.

[Bug] Support SSR for ApiItem

---

packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

Improper use of `includes` resulted in `taggedInfoObject` being `undefined`. This, in turn, led to a broken `link` config when setting `categoryLinkSource` to "info", which, in turn, resulted in `info` docs not associated to a sidebar.
Before:
```javascript
const taggedInfoObject = intros.find((i) =>
i.tags ? i.tags.includes(tag) : undefined
);
```
After:
```javascript
const taggedInfoObject = intros.find((i) =>
i.tags ? i.tags.find((t: any) => t.name === tag) : undefined
);
```
bug fix
tested with MT Monitor API using multi-spec
https://user-images.githubusercontent.com/9343811/199828973-344dbfe1-8c5d-44ca-85a4-4ac08a08d011.mov

[Bug] Use find instead of include to match tags

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

This change checks that the plugin is defined as an `Array` before attempting to access the first index.
See #315 for background
Valid plugin config variations:
```javascript
{
plugins: [
["@docusaurus/plugin-content-docs",options],
"./myPlugin",
["./myPlugin",{someOption: 42}],
function myPlugin() { },
[function myPlugin() { },options]
],
};
```
> Basically, the `getDocsPluginConfig()` function previously assumed that `plugins` would be defined as arrays. Since plugins may also be `functions` (defined locally) or `strings` this resulted in an error when we attempted to access the first index.

[Bug] Check if plugin is array before accessing first index

---

packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js

This PR consists of fixing `SchemaTabs` arrows not being rendered for Response examples. Currently, arrows are rendered when `SchemaTabs` are first mounted and satisfy the condition that `tabOffsetWidth < tabScrollWidth`. The issue is that this condition only applies to the first `SchemaTabs` ref and does not carry on to subsequent tabs with their respective `tabOffsetWidth` and `tabScrollWidth` values. To remedy this, the [ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) is used to accurately capture each `SchemaTabs` ref and their respective `tabOffsetWidth` and `tabScrollWidth` values.
Tested with Prisma Access Configuration API: 
- Tab through different response status codes and ensure arrows render on both sides of example tabs when necessary …

[Bug] SchemaTabs arrows not rendering for response examples

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/index.tsx

This PR addresses the issue of collapsing `ApiDemoPanel` when the user tries to submit an invalid request (ie. leaving required fields blank) through the 'Send API Request' button. 
> Note: Further implementation for handling input field validations is the ideal solution and will be introduced in a later PR, as this solution only prevents collapsing of the `ApiDemoPanel`.
See #316
Tested locally with [Petstore API | Find pet by ID](https://docusaurus-openapi-36b86--pr331-03i8bi4p.web.app/petstore/get-pet-by-id)
https://user-images.githubusercontent.com/48506502/200649522-c38647b4-3a4d-48b3-af8d-9c90ad8312fd.mov

[Bug] Prevent ApiDemoPanel collapse for invalid requests

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Added support for Algolia DocSearch
- Update posixPath to wrap path.join to fix backslash issue when buildi… ([#332](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/332))
- Prevent ApiDemoPanel collapse for invalid requests ([#331](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/331))
- Add algolia config ([#328](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/328))

Prepare release v1.4.3

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts

Add `x-examples` resolver for json-schema-merge-allof
Generate throw error: 
```
WARNING: failed to create example from schema object: Error: No resolver found for key x-examples. You can provide a resolver for this keyword in the options, or provide a default resolver.
[ERROR] Error: No resolver found for key x-examples. You can provide a resolver for this keyword in the options, or provide a default resolver.
```
in this case
```yaml
Test:
description: Test
allOf:
- $ref: '#/components/schemas/TestA'
- $ref: '#/components/schemas/TestB'
x-examples:
Example:
value:
test1: false
test2: false
TestA:
type: object
description: testA
properties:
test1:
type: boolean
example: false
required:
- test1
x-examples:
Example:
value:
test1: true
TestB:
type: object
description: TestB
properties: …
```

Fix error when allOf two refs

---

packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

This PR introduces better support for double quotes in `sidebar_label` frontmatter. The solution is to find and replace any double quotes in `title` with single quotes. Additionally, the mustache template was updated to always wrap the `sidebar_label` frontmatter in double quotes.
See #337 for background
Tested with Petstore API

[Bug] Handle double quotes in sidebar_label frontmatter

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

See #323 thread for background. Essentially, the plugin was creating tag docs for tags not actually referenced by an operation. This resulted in "orphaned" docs or docs without a sidebar which led to build errors.
The fix is to cross-check that a global/root tag is actually referenced in an operation prior to creating the tag doc item. A similar logic was applied to sidebars for consistency.

[Bug] Include global tags and tag docs only if referenced by operation

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/styles.css

* Adds support for `items.anyOf` and `items.oneOf`
* Adds missing return statement in `createProperties` that would have prevented `properties` from rendering in some cases
* Adds missing `--openapi-input-background` variable to `styles.css`
* Matches discriminator tab styles to schema tab styles for consistency
Addresses #343 
Tested with OpenAPI snippet shared in #343 
See deploy preview and #343 

[Bug] Add condition for handling arrays of discriminators

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Authorization/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/index.tsx

Allows whitespace in security scheme key/token/password input. 
See #350 for context
Tested with petstore API

[Enhancement] Allow whitespace in key/token/password input

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts

See #349 for context.
Adds missing condition for handling `item.allOf` that resolve to properties.
Tested with Sailpoint API spec.

[Bug] Improve support for items.allOf

---

packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js

Switching imports from relative paths to package-based paths introduced a webpack file-loader error. This patch redirects imports to `lib` directory such that the compiled modules are imported instead of the typescript ones.

[Bug] Import markdown utils from lib

---

demo/api.mustache
packages/docusaurus-plugin-openapi-docs/src/index.ts

Hides the edit URL by default for all generated API docs. Users will still have the option to use a `template` to set `custom_edit_url` to the desired value.
Should be considered an anti-pattern to encourage editing of generated MDX.
Tested with API Zoo.

Hide edit URL by default

---

demo/examples/petstore.yaml
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

Change the way we kebab case info page id's. Instead of taking the title, which likely has spaces, we will replace the spaces with `-` and push to lowercase. 
IoT was io-t 
APIs was ap-is 

kebab case fix for info pages

---

demo/api.mustache
demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.test.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx

Introduce support for specifying proxy URL/server.
Some APIs don't include the necessary CORS headers in which case a CORS proxy may be needed. Also, some APIs will require a proxy for other valid reasons.
Tested with Petstore API - see deploy preview (inspect Network tab to see the proxy URL in request)

[Enhancement] Add proxy support

---

packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts

Adding `resolveInternal` option when using `swagger2openapi` to convert Swagger 2.0 to oapi3.
Some `$ref` doesn't seem to get resolved without it.
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/372
After adding this option i ran the gen-commands and all `$ref`s seemed to have been resolved. The generated docs looked as expected.

Add resolveInternal to swagger2openapi options

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts

The creation of a request schema works incorrectly. If there is a request body with allOf refs there will be no correct request body.
It will fix bug

fix jsonSchemaMergeAllOf options in createRequestSchema

---

demo/examples/petstore.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/styles.css

Adds support for rendering `nullable` when set to `true`.
> Note: also refactored how `schema` is passed to `SchemaItem` to reduce need to parse `deprecated`, `description`, `nullable`, etc., from `schema` in markdown.
See #387 for background
See deploy preview. The `nullable` setting was added to select schema properties for testing.

Add support for nullable

---

demo/docusaurus.config.js
demo/sidebars.js
packages/docusaurus-plugin-openapi-docs/src/markdown/createArrayBracket.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/styles.css

Some schemas can implement more than one node type at the same level, such as `oneOf` and `properties`, or any other combination. This change introduces changes to how `createNodes` processes schemas. Previously, there was an ordered precedent applied whereby we exited after the first match. With these changes, now all node types will be collected in an array and returned together, in the order they were processed.
> Note: also includes improvements to how items/arrays are rendered
> Note: fixes formatting issues with example tab labels - basically, just leaves them as-is instead of attempting to un-camel-case and capitalize the first letter of each word
Preview: https://docusaurus-openapi-36b86--pr397-nr3rt8ms.web.app/
Addresses issue observed in the following endpoint, whereby only the …

[Bug] Support multiple same-level node types and improve items/array support

---

packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/styles.module.css

This PR introduces support for rendering `summary` and `description` for param schemas that contain multiple examples. In addition, users are now able to tab through the provided examples in order to minimize any UI bloating.
See #398 for context
Tested with https://gist.github.com/paulo-raca/c82e211f6b4218003fef2f957488b319#file-openapi-json
- Ensure build works as expected 
- CSS changes are only applied to `ParamsItem` that contained multiple examples
https://user-images.githubusercontent.com/48506502/217336874-09fe15c9-ed05-4155-9c3b-9d13b9838208.mov

[FR] Added support for summary and description for param schema examples

---

README.md
demo/docs/intro.mdx

Clarify that only OpenAPI 3.0 is supported so as not to imply 3.1 support.

Clarify support for OpenAPI 3.0

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/styles.module.css

Removes the double scroll bars by reverting `max-height` and `max-width` defined [here](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/767cb952ac9dbcd9ad48e15f362eb79754b080f6/packages/docusaurus-theme-openapi-docs/src/theme/styles.css#L160-L164). It may make more sense to remove that top-level style, but without knowing where it applies, this option fixes the issue and is less intrusive.
See #416 
Working in Chrome, Firefox, and Safari on Mac
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes if appropriate.
- [ x ] All new and existing tests passed.

Remove double scrollbars on codeblocks in code tabs

---

packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/index.ts
yarn.lock

Recent update to `@paloaltonetworks/postman-code-generators` introduced the `url` library which requires polyfills for webpack >=5. The theme webpack config didn't have a `fallback` defined for `url` which resulted in the following issue #409. To address #409 and help ensure similar issues don't occur in the future, this PR replaces the previous fallback pattern with the `NodePolyfillPlugin` which, ostensibly, handles polyfills for all applicable libraries that require them.
Fix #409 and help future proof the theme against polyfills-related errors.
Tested locally in demo. Besure to `yarn docusaurus clear` in between runs.

Implement NodePolyfillPlugin in theme webpack config

---

demo/docusaurus.config.js
packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js

Addresses #432 
Adds utility for converting/casting various data types to `String`:
* `undefined` or `null` will return `undefined`
* `Array` will be joined to a formatted string
* Everything else will be converted to `String`
> Tested with DNS Security spec to ensure no regression bugs

Improve handling of non-string default values

---

.github/workflows/codeql-analysis.yml
.github/workflows/deploy-preview.yml
.github/workflows/validate.yaml
packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js

Merge main into v2.0.0

---

demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js

Addresses #430 
Not so much a bug as it is an enhancement or opinionated approach to supporting missing `schema` or `schema.type` definitions.
> I did a bit more research and came across this thread: https://github.com/OAI/OpenAPI-Specification/issues/1657
After skimming through some of the responses/opinions, I think there's a strong case/consensus around interpreting no 
schema.type as "any" - or, basically leaving it up to the tooling to decide how to handle those cases.

Handle missing params/header schema

---

demo/examples/petstore.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/styles.css

Addresses #411 and also tries to introduce complete support for all security types.

Fix security schemes

---

demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/markdown/createHeading.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/styles.css

See #419 for background
> Also introduces `openpai__heading` style.

Convert title heading from h2 to h1 for better a11y

---

demo/package.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json
yarn.lock

Locking compatible Docusaurus versions.
Docusaurus 2.3.0 introduced breaking changes that will not be supported in the `docusaurus-openapi-docs` 1.x.x release train. Instead, support for 2.3.0 will be introduced in the upcoming `docusaurus-openapi-docs` v2.0.0.
After merging, the plan is to test the canary release against a template and vanilla Docusaurus project.

Lock supported docusaurus versions

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts

Addresses #448 
Also, this PR introduces a change to how we capture the `firstBody` which will allow mime types with no `schema` to render as "any" instead of `undefined`.

Expand support for nullable objects and default to any for empty/unknown schemas

---

demo/api.mustache
demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx

Introduces `hideSendButton` option for manually hiding `Send Request` button.
Gives users option to disable "try it" feature.
See deploy preview.

[Enhancement] Add option to hide send button

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Add support for security vendor extensions ([#457](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/457))
- [Enhancement] Add option to hide send button ([#456](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/456))
- Lock supported docusaurus versions ([#449](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/449))
- Handle missing params/header schema ([#446](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/446))
- Apply docusaurus.io styles to demo ([#443](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/443))
- [FR] Added support for summary and description for param schema examples ([#406](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/406))
Other enhancements and …

Prepare release v1.6.0

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css

Addresses #460 
This PR consists of added support for styling response tabs based on the status code. Previously, the `responseTabDotStyle` was scoped to response tab dots, but has now been renamed and moved to the parent element to allow styling of the base response tab item.
Tested with Petstore API and styled tabs based on the `responseStatusStyle`
https://user-images.githubusercontent.com/48506502/221682102-ae73b2a3-e1ed-4065-bde9-48cbbcc9b147.mov

[FR] Add class to response tabs to differentiate success/error

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts

Previously, the plugin was only handling `additionalProperties` with no schema/properties defined, i.e. only a `type`. This change introduces support for rendering `additionalProperties` schemas, e.g. `properties`, `items`, etc., when present.
> Note: generated schema samples for additionalProperties is not supported but will be covered/added in a future PR
Expanded support for `additionalProperties`.
Tested with CSPM Anomalies API spec.

Add support for rendering additionalProperties schemas

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Add support for rendering additionalProperties schemas ([#465](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/465))
- Add response status class name to response tab item ([#461](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/461))
- Update usage docs ([#463](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/463))
- Allow "none" option for categoryLinkSource ([#462](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/462))
- Eval guard value as double not ([#468](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/468))
- Add code, thead and tbody to greaterThan regex ([#459](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/459))

Prepare release v1.6.1

---

packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts

Referenced in #453 
FYI, we may need to revisit this in the future, depending on the variations we see in inline HTML in generated MDX

Add `bold`, `svg` filtering and ensure parity between opening/closing regex

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Add support for Docusaurus 2.3.0 ([#471](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/471))
- [UI Enhancement] Move MethodEndpoint from ApiDemoPanel to left doc panel ([#429](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/429))
- [UI Enhancement] Migration to SCSS and BEM-style convention for theme components ([#450](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/450))
- [UI Enhancement] Include status code tabs in Response card ([#476](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/476))
- Split beta release into separate script/workflow ([#480](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/480))
- Add bold, svg and ensure parity between …

Prepare release v2.0.0-beta.0

---

packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/_DiscriminatorTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss
packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/_ParamsItem.scss
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/_SchemaItem.scss
packages/docusaurus-theme-openapi-docs/src/theme/styles.scss

Re-colors tree lines with `--ifm-toc-border-color` and allows details schema/params/discriminator items to be full width
Improve UI/UX
See preview

[UI Enhancement] Restyle tree lines

---

demo/docusaurus.config.js
packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/styles.css
yarn.lock

See #499 for background
This PR also introduces the following changes:
* Adds `title` to Code Blocks that displays `language / variant`
* Changes the BASH/cURL logo to something more appropriate (hopefully)

[Enhancement] Add support for powershell

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/styles.css

See #496 for background. Essentially, this change removes redundant styles that are the likely cause of the "double scrollbars" reported by users.
Only one set of x/y scrollbars should be visible. Having more than one set is a poor UI/UX.

[Bug] Fix double scrollbars

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx

Undos the unintended deletion of the response status/headers tabs. Also applies the `max-height` styles to `code` so responses overflow properly.

[Bug] Add missing status/headers tabs and apply max-height to code

---

packages/docusaurus-theme-openapi-docs/src/index.ts

Our SASS loader rules in our webpack config appear to be too broad which could lead to conflicts/issues with `docusaurus-plugin-sass`. This PR attempts to solve for this by refining/narrowing the loader rules such that we specifically test and load only the `styles.scss` included in `docusaurus-theme-openapi-docs`. 
See https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/discussions/488#discussioncomment-5404790 for additional context
Deploy preview will test that the rule functions as expected. Additional testing with standalone site is required to confirm our theme can work alongside `docusaurus-plugin-sass` without issues.

[Bug] Narrow SASS loader rules to avoid conflicts with docusaurus-plugin-sass

---

packages/docusaurus-theme-openapi-docs/src/index.ts

Point `test` and `include` to `lib` directory which appears to be where webpack searches for `styles.scss`.

[Bug] Patch webpack sass loader

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/styles.scss

* Replace Linux with BASH logo for cURL code tab
* Reduce size of code tab logos
* Implement variables for defining logo width/height

Update bash/curl logo and refactor how logo width/height are defined

---

README.md
demo/api.mustache
demo/docs/intro.mdx
packages/docusaurus-plugin-openapi-docs/README.md
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createVendorExtensions.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts

Adds support for rendering arbitrary vendor extensions at the operation level.
Previously, we were displaying extensions for some of our product APIs:
Tested with the CWPP OpenAPI spec.

[Enhancement] Add support for rendering vendor extensions

---

packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthorization.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss

This change moves the `Authorization` card from the demo/explorer panel over to ApiItem.
> A good post-cleanup step would be to cleanup the component naming. For example, we use "security schemes" and "authorization" and "security" interchangeably but perhaps there's a more intuitive/accurate naming we can apply to these componens.
The contents of Authorization are align more with reference documentation as opposed to anything demo/explorer specific. In other words, the content is read-only and has no bearing on the final API request that gets sent from browser. Therefore, it makes sense to move it under the reference docs column. The added benefit is that the API demo/explorer panel will be less crowded.

[UI Enhancement] Move authorization card to ApiItem

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx

Moves the CodeTabs section above the Request section. Also brought back a pattern that @blindaa121 implemented before for spacing the tabs.
Analytics indicates that CodeTabs see much more usage compared to the "Send API Request" feature so it might make more sense to make it more easily accessible to users. Additionally, after reviewing a number of other API doc tools, this appears to be the most common pattern/layout.

[UI Enhancement] Move CodeTabs above Request

---

packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss

Replaces the details marker with a more appropriate caret symbol. Should only apply to details in the reference/ApiItem column.
Cleaner, more consistent style

[UI Enhancement] Restyle details markers with caret

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/styles.scss

Preview: https://docusaurus-openapi-36b86--pr542-38trpp5r.web.app/petstore_versioned/add-pet
This PR consists of updated styling for code language selection tabs with efforts in improving UI/UX where the language now renders below their respective logo to increase accessibility in the event that the logo image fails to load. Additional support for languages with multiple variants are now rendered as tabs below the selected language when available.
Tested locally with Petstore API
https://user-images.githubusercontent.com/48506502/231610291-91bd2890-ffaa-451e-860c-b6bff0578dab.mov

[UI Enhancement] Response Examples: Updated styling and support for multiple language variants

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Remove PWA ([#548](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/548))
- Add classnames to MethodEndpoint ([#541](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/541))
- [Enhancement] Add support for rendering vendor extensions ([#527](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/527))
- Update deploy preview workflow

Prepare release v1.7.1

---

packages/docusaurus-plugin-openapi-docs/package.json
yarn.lock

Upgrades dependencies. Most notably, it upgrades `@apidevtools/json-schema-ref-parser` to `10.1.0` release which does not include breaking node engine change introduced in `9.x` train.

Upgrade dependencies

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Upgrade redocly-core and json-schema-ref-parser ([#551](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/551))

Prepare release v1.7.2

---

packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts

Add footprint formation when resolving references fails
I opened an issue (https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/559) because I received an error that looked like there was something wrong in the plugin, but it turned out to be a typo in my project somewhere. Adding the footprint allows developers to see where in the spec something failed.
Below message was reported which didn't help me too much.
```js
Could not find resolver for "g:/[somepath...]/ApiCommons.yml%22"
SyntaxError: Unexpected token u in JSON at position 0
WARNING: the following OpenAPI spec returned undefined: G:/[somepath...]/Api.yml
```
Built the plugin and referenced it in my project, caused it to fail and that resulted in a better error that helps me find out where the error is.
```js
Error: …
```

Add more debug info to resolveJsonRefs

---

demo/docs/intro.mdx
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts

This PR adds an optional `markdownGenerators` config option to the `docusaurus-plugin-openapi-docs` plugin, allowing the user to optionally provide their own `createApiPageMD`, `createInfoPageMD`, or `createTagPageMD` functions. If not provided, the plugin defaults to the existing functions of the same name.
This change allows for a high level of customization for layout and styling. While the `template` config option exists, it doesn't allow for large layout changes since the `markdown` available for the template is already generated by the `createApiPageMD`, `createInfoPageMD`, and `createTagPageMD` functions.
I installed a fresh Docusaurus site with this update, passing in the different config options for `markdownGenerators` that return strings with different content or layouts than …

Add optional `markdownGenerators` config option

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

- Add optional `markdownGenerators` config option ([#567](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/567))
- Add more debug info to resolveJsonRefs ([#560](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/560))
- [Bug] Add handler for oneOf properties, fix nested `<li>` and avoid duplicate properties in createAnyOneOf ([#561](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/561))

Prepare release v1.7.3

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts

See [this thread](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/555#issuecomment-1537045129) for background.
> Note: it's best to test using one of the Resoto specs

[Bug] Use SchemaItem to render leaf discriminator properties/nodes

---

packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx

As the OpenAPI spec size increases we run the risk of exceeding the max string length allowed for `server.bundle.js`. This change uses `zlib` to compress the `api` frontmatter prop in order to reduce the overall size of this string.

Adds compression support to frontmatter api prop

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Body/index.tsx

As mentioned in #611 , this is a minimal setup to unify the tabs. We could think about changing the var names and so on, but I wanted to wait for your approval first.
Mentioned in #611

Unify tabs naming

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/makeRequest.ts

See #618 
The current implementation doesn't support the FormData request well - at least sending binary files doesn't work at all.
There are 2 main problems:
1. The request body is initially serialized to JSON
1. The request Content-Type header is set manually instead of letting `fetch` to set it automatically based on the content. `fetch` should also set the correct boundary separator (eg `multipart/form-data; boundary=---...`). 
See #618 

Fix demo panel for `FormData` request type

---

packages/docusaurus-theme-openapi-docs/package.json
yarn.lock

`sass-loader` was used from a sub-dependency but called directly in the module
Fix #638 
Tested on a project that uses pnpm8 as package manager. The build passes when it used to not pass.

Use `sass-loader` module as dependency

---

.eslintrc.js
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.test.ts

`createAnyOneOfProperty` has an incomplete implementation and doesn't display all possible types at the moment, but only 'object' type. Reusing `createAnyOneOf` helps with making it display all possible mods.
A bug in `createAnyOneOfProperty` prevents from seeing all mods and shows `MOD1`, `MOD2`, etc for primitive types and arrays.
See the snapshot of the before and after:
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/commit/55a26858333f83b109868c931d63a55ec58b50d7

Reuse `createAnyOneOf` while creating a property

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Body/index.tsx

See https://github.com/PaloAltoNetworks/pan.dev/issues/512 for background.
Tested with AdoptionAdvisor API spec: https://raw.githubusercontent.com/PaloAltoNetworks/pan.dev/115152a5f4bc8c5cdb646a4f373ee5529088087d/openapi-specs/cspm/AdoptionAdvisor.json

Allow charset support for application/json

---

packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json
yarn.lock

Stop Docusaurus support at v2.4.0
Docusaurus v2.4.1+ introduced breaking changes to v2.0.0 plugin. Will revisit after v2 stable is released.

stop docusaurus support at v2.4.0

---

demo/package.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json
yarn.lock

Upgrades packages to support Docusaurus 2.4.3
In preparation for stable release and promotion of v2.0.0 branch to default.
Tested with demo. See deploy preview for live test.
TODO:
Address the following warning observed in console. I suspect it could be caused by a third-party package as the OpenAPI theme does not implement the render method.
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more
```
> Note that the warning does not appear in a production build

Upgrade to React 18 and support Docusaurus >=2.4.1 <=2.4.3

---

demo/docusaurus.config.js
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/makeRequest.ts

Improves support for handling multi-part form data in `makeRequest` module. Previously, payloads that included a file/blob excluded other form data. Additionally, blob content returned by API was simply rendered in raw format in the response card.
With these changes, media content types will now be auto-downloaded to file.ext, where ext is the appropriate file extension for that type.

Improve support for handling multipart form data

---

package.json
packages/docusaurus-plugin-openapi-docs/src/markdown/createCallbacks.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestBodyDetails.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/_OperationTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/styles.scss

OpenAPI specs callbacks in endpoints were being ignored on rendering. I noticed the types were included but no code was found for rendering the callbacks. So `callbacks` included in [Petstore](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/examples/petstore.yaml) cannot be seen at https://docusaurus-openapi.tryingpan.dev/petstore/subscribe-to-the-store-events
Be aligned with OpenAPI 3.0 Specs: https://swagger.io/docs/specification/callbacks/
Go to petstore "Subscribe to the store events"  - http://localhost:3000/petstore/subscribe-to-the-store-events

Add Callbacks Support to V3

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/languages.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeTabs/index.tsx

Use merged languages to have updated set of languages on change language and code tabs
Fix an issue when switching from a non custom code sample language tab to a custom code sample one
https://docusaurus-openapi-36b86--pr660-xou63k6x.web.app/petstore/add-pet, switching from Java to PHP for example

Fix x-codeSamples load when switching language tabs in V3

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createCallbacks.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createHeading.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestHeader.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/_ApiTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/_OperationTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/_SchemaTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/styles.scss

Normalize `@theme/Heading` component usage
Due to headings creation using html elements, some headings didn't have classnames or had different classnames across the markdown pages. This was preventing or making more difficult to customize styles when using this library
Check the following pages Headings H1 and H2:
- Go to /petstore/swagger-petstore-yaml and check `Swagger Petstore YAML`, `Authentication`
- Go to /petstore/subscribe-to-the-store-events and check `Request`, `Responses`, `Callbacks`

fix: markdown pages heading creation

---

demo/examples/petstore.yaml
packages/docusaurus-theme-openapi-docs/src/markdown/utils.test.ts
packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js

Fixed the guard to allow anything not undefined or empty to avoid issues with boolean and 0 numbers.
Fix #724.
* Added unit tests for the utils file
* Updated the demo project with a default value at 0 to see the impact. See screenshot for before and after changes.
Before the fix:
After the fix:

fix: guard only undefined and empty strings

---

.gitignore
README.md
demo/docs/intro.mdx
demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/README.md
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx

Adds support for schema/model definition pages which are generated when `showSchemas` is set to `true`.
The out-of-the-box behavior is kept the same - no schema pages.
I am a SE over from [Canopy Connect](https://www.usecanopy.com), and we are looking to take our [documentation](https://docs.usecanopy.com/reference/getting-started) to the next level. After some considerations (Readme - current, Docusaurus, Mintlify, Starlight Astro) I believe Docusaurus to be one of the best options, expect for the fact that this openapi plugin doesn't have schema pages, which we require. I'm hoping to help push this along so we can make our switch to Docusaurus.
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/713
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/225 …

feat: Implement schema pages behind a config option `showSchemas`

---

packages/docusaurus-plugin-openapi-docs/package.json
yarn.lock

Upgrades OpenAPI parsers to latest release.
Apply patches/bug fixes and improve OpenAPI 3.1 support
Tested with both OpenAPI 3.0 and 3.1 specs.
> Note, there is no guarantee docusaurus-openapi-docs will support all OpenAPI 3.1 features with this change. Support for some features may require additional development work.

Upgrade OpenAPI parsers

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/index.js
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js

Use `requestAnimationFrame` to sync resize observer to frame rate.
Helps avoid resize observer loop/notification errors.
Tested using the Petstore info page, where the error was observed locally.

[bug] Ensure resize observer is calculated once per frame to avoid loops

---

packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

Uncomments line that extracts and groups operation tags with global tags.
Commenting this line prevented tag grouping when no global tags were defined in the OpenAPi spec.
See #762 
This regression bug was introdudced in #737 
Tested by commenting out globally defined groups in petstore OpenAPI spec. When doing so, the plugin generates tag groupings using the operation tags.

Uncomment line preventing grouping by operation tags

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/schema.ts

Address bug preventing qualifier and type (schemaName) from properly rendering for allOf schemas.
See https://github.com/PaloAltoNetworks/pan.dev/issues/587
Tested using the OpenAPI snippet in https://github.com/PaloAltoNetworks/pan.dev/issues/587

Fix allOf schema qualifier and type

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Fix for ensuring required properties with nested `allOf` are evaluated properly.
See https://github.com/PaloAltoNetworks/pan.dev/issues/588 for background. The fix basically moves to honoring the initial `required` eval we get when traversing properties, rather than basing it on the resolved `required` we were getting from the `mergeAllOf` function.
Tested using the OpenAPI snippet shared in https://github.com/PaloAltoNetworks/pan.dev/issues/588

Ensure correct eval of required properties with nested allOf

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/_ApiTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/_DiscriminatorTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/_MimeTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/_OperationTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/_SchemaTabs.scss

This PR addresses https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/272, where empty scroll bars for tab components are being rendered within Firefox browsers.
The `scrollbar-width: none` property has been added to the following classes: 
- `.openapi-tabs__response-list-container`
- `.openapi-tabs__discriminator-list-container`
- `.openapi-tabs__mime-list-container`
- `.openapi-tabs__operation-list-container`
- `.openapi-tabs__schema-list-container`
The scrollbars should not be rendered if it is not necessary.
**Browser:** Firefox
Tested locally by navigating to http://localhost:3000/petstore_versioned/add-pet and ensuring empty scroll bars are not being rendered.

[UI Bug Fix] Firefox issue: Hide empty scrollbar track from Tab components 

---

README.md
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts

This allows a custom plugin, other than the default `@docusaurus/plugin-content-docs`, to render the generated OpenAPI docs.
In our Wiki, we have a custom plugin that renders our documentation. Although the plugin is based on `@docusaurus/plugin-content-docs`, it is named differently. Therefore, it couldn't be used to render OpenAPI docs because `@docusaurus/plugin-content-docs` is hard coded in the lookup logic of this plugin. The proposed change allows for a custom plugin, with `@docusaurus/plugin-content-docs` as default to maintain backward compatibility.
We use it in our own Docusaurus build [here](https://github.com/iotaledger/iota-wiki/blob/v3/docusaurus.config.js#L250).

Allow custom plugin to render

---

demo/docs/intro.mdx

Myself and others were not able to install the beta plugin properly. I think it's because we were skipping past the information about installing both the plugin and the theme. I changed them to headings. Take it or leave it.
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/discussions/735
- [ X] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
- [ NA] I have added tests to cover my changes if appropriate.
- [NA ] All new and existing tests passed.

changed theme and plugin to headings

---

demo/docusaurus.config.js
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx

See #692 for background.
Allows users to disable compression to avoid differences in compressed frontmatter `api` output between local and CI operating system.
Tested using petstore API

Add option to disable frontmatter api prop compression

---

.vscode/settings.json
packages/docusaurus-plugin-openapi-docs/src/index.ts

* Ensure `sidebars.ts` is removed when performing clean
* Move to recursively deleting generated `schemas` directory
See #811 for background. Concerning `schemas`, I observed the `schemas` directory was left behind after the schemas MDX files were cleaned. Instead of attempting to first clean the MDX files followed by the container directory, I opted to perform a recursive removal of the entire directory.
Tested locally using example API specs.

Ensure sidebars.ts and schemas are properly cleaned

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

Running `clean-api-docs` doesn't delete the generated sidebar.ts file, this causes the file to not carry over changes when `gen-api-docs` is ran. For now I have install & use `rimraf` to delete the sidebar.ts `docusaurus clean-api-docs all && rimraf <path>/sidebar.ts`
Used the local version of this branch in my typescript Docusaurus project, and confirmed `clean-api-docs` now deletes the sidebar.ts file without needing `rimraf`.
Updates the glob string used to match `sidebar` files.
Originally `"sidebar.js"` was used. I updated it to `"sidebar.{js,ts}"`
You can test this glob [here](https://www.digitalocean.com/community/tools/glob?comments=true&glob=sidebar.%7Bjs%2Cts%7D&matches=false&tests=foobar.js&tests=foobar.ts&tests=sidebar.js&tes …

Fix clean-api-docs not deleting sidebar.ts

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx

Adding `docItemComponent: "@theme/ApiItem"` in the docusaurus config causes undesired behavior in the website, including pages that are completely unrelated to the api.
After investigation, it seems that the main div in each page is missing the `markdown` classname, causing the following changes in all pages of the site:
1. My `h2` headers change size.
2. My `h2` headers' margins change.
If I inspect the page, and add the `markdown` classname to the div, the original styling is applied and all is good.
This issue affects the styling of the entire docusaurus website, including pages that are unrelated to the api.
Tested using Docusaurus V3, using the latest V3 beta of this library.
Here is what the site looks like **without** the library:
<br/>
Here is what the site looks like **with** the …

Fix - @theme/ApiItem causes undesired website-wide style changes

---

packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts

fix markdown table within the description attribute cannot be rendered correctly
The "|" character within the description attribute is being escaped, which causes the markdown table to not render correctly.

fix: markdown table within the description attribute cannot be rendered correctly

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/index.tsx

adds a row wrapper for col classes to ensure proper padding
fix a bug, which is also available on the demo site

fix col row padding footer&pagination

---

demo/docs/customization/styling.md
demo/docs/sidebars.md
demo/examples/petstore.yaml
demo/src/css/custom.css
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/__fixtures__/examples/openapi.yaml
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.test.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

This change enables schemas to have `x-tags` defined for them, which allows them to be grouped alongside related path objects when `sidebarOptions.groupPathsBy: 'tag'` is configured.
In reporting the unexpected behavior in #836, I began poking around and discovered [the `x-tags` extension by redocly](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tags/). It seems like a useful feature, and was easy enough to get working.
It's intended (by redocly, and so here) that it's a "competing" option for configuring `showSchemas: true`, which is why you'll see some changes to the checks/logic in `openapi/openapi.ts` surrounding if/when to add schema objects to the sidebar slice.
Tested this on my local computer, using the demo app. I've added (only locally, I think) `x-tags` …

Implement the `x-tags` extension for schema objects

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Response/index.tsx

Transparent background when displaying response placeholder

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Addresses #830 and related issues
The fix was to move the readOnly/writeOnly checks to the front to ensure they are evaluated first.

ensure readOnly/writeOnly are evaluated first

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Addresses #813 
Effectively adds support for empty object schemas. Tested in both request and response including schema items.

Support empty object schemas

---

packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts

Handle various schemas inside `additionalProperties` correctly (as far as I can tell).
Trying to fix issues I have with properly displaying types in `additionalProperties`.
In unit tests and documentation.

handle various additionalProperties cases

---

packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

Same as #853, but against the `main` branch

Avoid concatenating all tags when grouped by tagGroups

---

packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

Before concatenating the `apiTags`, `operationTags`, and `schemaTags`, the `sidebars/index.ts` file now checks to make sure that `gropuPathsBy` is not "tagGroup." This prevents the undesired tag categories from being added to the tagGroup category.
As reported in #792, using `groupBy: "tagGroups"` still leaves the sidebar with extra, undesired tags categories inside each tagGroup category. This PR resolves that, in the v3 branch.
Locally, I've inspected the running dev site. I've run `yarn test`, and everything still passes. 

[V3] Avoid concatenating all tags when grouped by tagGroups

---

demo/docs/sidebars.md
demo/docusaurus.config.js
demo/examples/food/restaurant/openapi.yaml
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts

The `groupByTags()` function in `sidebars/index.ts` is already generating the Schemas category for both `groupBy: "tag"` and `groupBy: "tagGroup"`. It seems like the simplest, least disruptive way of accomplishing what I wanted was to utilize the Schemas category _after_ `groupByTags()` was finished going through all the tagGroups.
In the case of tagGroups, now, it moves the "Schemas" category (if any) from the first tagGroup category (since all the schema categories are identical anyway) to the end of the sidebar, as a "sibling" to all the tagGroup categories. Then, it discards the "Schemas" category from _all_ of the tagGroup categories.
As reported in #836, an extra Schemas category is currently placed inside ever tagGroup category if `showSchemas: true` is configured. This PR aims …

Fix tagGroup display when showSchemas is configured

---

demo/docusaurus.config.ts
packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-plugin-openapi-docs/src/types.ts

Credit to #856 for the solution. Addresses #855

Support custom downloadUrl for versions

---

demo/docusaurus.config.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/languages.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/persistanceMiddleware.ts

Addresses #826 
* support custom code snippet ordering
* support custom postman code generator options
tested using petstore API

Support flexible code snippet ordering and options

---

README.md

Update Readme.md file about missing configuration in the versioned section.
Update documentation to markdown the changes.
N/A
Added a new row in versions configuration 
`| `downloadUrl` | `string` | `null`  | _Optional:_ Designated URL for downloading OpenAPI specification for versioned.                                          |
`

[Chore] Update readme for 3.0.1 release

---

demo/examples/petstore.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Addresses issue reported in #889 
This adds fix to v2.0.0 branch. Will port to v3 and address the remaining formatting issues.

Add support for anyoneof object primitive

---

demo/examples/petstore.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Support anyOf/oneOf schema descriptions

---

demo/examples/petstore.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Body/index.tsx

Fix support for example summaries

---

demo/docusaurus.config.ts
demo/examples/tests/allOf.yaml
demo/sidebars.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Addresses #902 and proposed fix in #903. The root cause appeared to stem from the order in which same-level properties and allOf were being evaluated which led to the properties being ignored.
I added a small test to cover this case with plans to add coverage for additional variations in a later PR.

Ensure same-level properties and allOf are rendered 

---

CHANGELOG.md
README.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/README.md
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

Prepare release v2.2.2

---

demo/examples/tests/oneOf.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts

Adds coverage for additional oneOf test cases. Tests cases not supported are commented out for future work.

Add additional oneOf test cases

---

demo/examples/tests/discriminator.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Addresses a bug where discriminator properties with no `mapping` were not rendered/returned. Going forward, the plugin will handle/render these cases as "simple" properties, similar to how Swagger UI and Redoc handle them.
> Note: this fix will be backported to v2 in support of pan.dev
> Note: additional fixes coming for broken cases highlighted in new tests

Render discriminator with no mapping as simply propert

---

packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json
yarn.lock

As mentioned in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/911#issuecomment-2310196773, I attempted to update both docusaurus and this plugin, and got some errors like `Hook useScrollController is called outside the <ScrollControllerProvider>.`. I checked my lockfile, and found that I had old versions of docusaurus packages installed alongside the newer versions, and they were coming from this plugin.  
Honestly I didn't test this, I just think it's the correct fix.  

Update dependencies for docusaurus 3.5+

---

demo/examples/tests/anyOf.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

* Add support for `oneOf` within `anyOf` when generating a schema
My schema looks like this:
```yaml
MySchema:
properties:
some_property:
anyOf:
- oneOf:
- $ref: '#/components/schemas/SchemaPartA'
- $ref: '#/components/schemas/SchemaPartB'
title: Either of SchemaPartA or SchemaPartB
- type: 'null'
```
Currently, when I generate MySchema, the SchemaTabs component has no children which causes the page to crash. I added a workaround for that to SchemaTabs, i.e. `if (!children?.length) return null`.
This PR aims to add support for nested `oneOf` constructs within `anyOf` in a schema.
I realise that the same could be expressed as below, but the schema is generated from FastAPI and I have less control over changing that. As far as I can tell, the schema snippet above is valid.
```
anyOf:
- …
```

Fix bug where oneOf within anyOf would not be rendered in request schemas

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createCallbackMethodEndpoint.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createCallbacks.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/MethodEndpoint/index.tsx

This adds a new prop to the MethodEndpoint component to give it context as to where it is rendering. If the context is `callback` it does not prepend the serverUrl, any other context and the serverUrl is prepended. 
Callback methods are rendering the path of the endpoint with the server URL which is incorrect. The callback section should only render the endpoint the spec defines. For example in the petstore versioned spec, the plugin currently renders this url in the method endpoint component `https://petstore.swagger.io/v2http://notificationServer.com?url={$request.body#/callbackUrl}&event={$request.body#/eventName}` 
The [OpenAPI specs section on callbacks](https://swagger.io/docs/specification/callbacks/) details that it's possible for this endpoint value to reference the requestBody …

Dont render serverUrl on callbacks MethodEndpoint component

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/MethodEndpoint/index.tsx

Imports hooks from theme as opposed to relative path to avoid import error when swizzling component.

Import MethodEndpoint hooks from @theme

---

demo/docs/customization/languagetabs.mdx
demo/docs/customization/styling.mdx
demo/src/css/custom.css
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/languages.ts

Fixes an issue that prevented all user-defined `languageTabs` options from merging. Prior to this, only `variants` were respected. After this change, all options, including `highlight`, `logoClass`, etc., will be respected.

Supporting merging all user defined languageTabs options

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/_Request.scss
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/index.tsx

Similar to #673, adds missing `SecuritySchemes` component back to `ApiExplorer`. Still not certain when this was removed but it was likely when the migration to ApiExplorer occurred.

Add missing security schemes component

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.tsx
yarn.lock

Addresses #955 
It seems we missed an edge case where default values of "false" or "[]" failed to guard and/or render as expected. In the case of the latter, "[]" resulted in an empty string.
Tested with the OpenAPI spec provided in referenced issue.

render default value as string literal instead of markdown

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ParamOptions/index.tsx

Fix #798 
The button `Show optional parameters` is in a form, so [it's type is default to `submit`
](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type).
Since, we don't want to submit form in this case, we need to change button type to `button`.
Tested on local env
**To reproduce**
https://github.com/user-attachments/assets/4dc5d7f7-23c2-4be3-941a-bda5bc24e65d
This can be reproduced on https://docusaurus-openapi.tryingpan.dev/cos/list-buckets
**After fixed**
https://github.com/user-attachments/assets/e246e72d-3434-44eb-a4a7-4cc26c3ee7f8

Fix change type of Show optional parameters button

---

demo/examples/tests/enumDescriptions.yaml
packages/docusaurus-plugin-openapi-docs/src/markdown/createParamsDetails.ts

#951 added support for `x-enumDescriptions` but it on get `x-enumDescriptions` on parameter with schema type array. This pull add support for other schema type.
Additional enhancement for #951 
Tested by adding a test schema `demo/examples/tests/enumDescriptions.yaml`

Support enum descriptions in schema object

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeTabs/index.tsx

On mobile/smaller viewports, scrollIntoView caused the entire page to scroll to active code snippet tab. This change implements scrollLeft to ensure the active tab is visible when the user scrolls without scrolling the entire page.
Before:
https://github.com/user-attachments/assets/73f11a13-1534-483f-93a8-7a3ee0155f7f
After:
https://github.com/user-attachments/assets/2cb0de3f-fceb-4d3d-a8d8-42a355dd31bf

Use scrollLeft to avoid scrolling entire page to active code tab

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

Prepare release v4.1.0

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx

The CodeSnippets component had a bug where the condition for checking the selectedVariant was incorrect. This commit fixes the bug by adding a null check for the language variant.
An error occurs in the CodeSnippets component when languageTabs is empty in `docusaurus.config.ts`.
Previously, CodeSnippets was not rendered.
``` docusaurus.config.ts
languageTabs: [],
```
I set languageTabs to empty and confirmed that it was rendering the same as before without any errors in local.

chore: Fix bug in CodeSnippets component

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createContactInfo.ts

The protocol was set to mailto even though it was a URL.
The contact.url link was a mailto link.
According to OAS specifications, it should be a link to the inquiry form screen
_https://swagger.io/specification/_
_After correction_

fix: Fix bug in createContactInfo.ts

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts

Fix allOf in the API response for objects.
Fixing https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/806
- Modified demo to local specs.
- Tested and revert back to same demo specs.
N/A

[Fix] all of items in array for api response

---

demo/examples/tests/additionalProperties.yaml
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx

Addresses regression bug where additionalProperties object primitives were not rendered. Also adds additionalProperties examples to tests.

Ensure additionalProperties object primitives are rendered

---

packages/docusaurus-plugin-openapi-docs/src/index.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
packages/docusaurus-plugin-openapi-docs/src/options.ts
packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/styles.module.css
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
yarn.lock

Migrates to new `Schema` theme component for rendering schemas in schema pages and refactors layout as described in #996. Also allows use of `createSchemaPageMD` when defining markdown generators.
Ensures consistency in how schemas are represented across API and schema pages.

Migrate schema page to Schema component and refactor layout

---

cypress/integration/__snapshots__/testSchemaSnapshots.spec.ts.snap
packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/_ApiTabs.scss
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx

Long overdue improvements to how discriminator schemas are handled. 
Important notes:
* In the event that the discriminator property is defined at both the parent and sub schema levels, the plugin will attempt to merge the sub schema property into the parent

improve handling of discriminators

---

CHANGELOG.md
README.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

Prepare release v4.2.0

---

README.md
demo/docusaurus.config.ts
demo/package.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json
yarn.lock

Upgrade to Docusaurus v3.6 - Enable [Docusaurus Faster](https://github.com/facebook/docusaurus/issues/10556)
It's faster, see https://github.com/facebook/docusaurus/issues/10556
Cold builds - almost 3x faster:
```bash
hyperfine --prepare 'yarn workspace demo clear' --runs 3 'DOCUSAURUS_FASTER=false yarn build-demo' 'DOCUSAURUS_FASTER=true yarn build-demo'
Benchmark 1: DOCUSAURUS_FASTER=false yarn build-demo
Time (mean ± σ):     26.049 s ±  0.252 s    [User: 49.003 s, System: 5.959 s]
Range (min … max):   25.885 s … 26.340 s    3 runs
Benchmark 2: DOCUSAURUS_FASTER=true yarn build-demo
Time (mean ± σ):      9.726 s ±  0.063 s    [User: 16.771 s, System: 2.176 s]
Range (min … max):    9.661 s …  9.787 s    3 runs
Summary
DOCUSAURUS_FASTER=true yarn build-demo ran
2.68 ± 0.03 times faster …
```

Docusaurus v3.6 - enable Docusaurus Faster

---

demo/examples/petstore-1.0.0.yaml
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.tsx

Support an array of schema types (IE string & null)
- We are trying to switch away from readme.com which supports array of schema types
Used the pet store demo to test - http://localhost:3000/petstore_versioned/1.0.0/update-pet-with-form
```yaml
type:
- string
- 'null'
```
```json
"type": [
"string",
"null"
]
```
Before the above schemas would result in `stringnull`, now they result in `string | null`
Before:
After:

Support schemas with array of types

---

packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

I'm trying to add this plugin to Backstage's docsite to automatically show OpenAPI-documented APIs (PR: https://github.com/backstage/backstage/pull/27573). I noticed that this package was causing a lot of lockfile churn and bringing in versions that I would expect to be duplicates, but aren't.
Locally linked this into my Backstage fork and verified that no additional docusaurus dependencies were duplicated, there was only a single version of each dep.
This is my first contribution to this repo, so please share any additional testing steps I should be taking here 🙇 .

fix: move dependencies to peer dependencies

---

packages/docusaurus-theme-openapi-docs/package.json

Fixes https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/1019#issuecomment-2478563994.
I think I was a little aggressive initially in moving deps to peer deps, let's move this one back.

fix: add back @hookform/error-message as a regular dep

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ApiCodeBlock/Line/_Line.scss

This PR consists of removing the global selector and class name selector (`.theme-code-block-highlighted-line`) defined in `Line.scss`, as this class name is no longer being used in the project.
See https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1021 for context. 
Tested by ensuring styles were not affected for the `CodeBlock` component and warnings mentioned in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1021 have been cleared.

Remove unused global selector

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/createTermsOfService.ts

Addresses the warnings seen when performing production build:
```
[WARNING] Docusaurus static site generation process emitted warnings for 4 paths
This is non-critical and can be disabled with DOCUSAURUS_IGNORE_SSG_WARNINGS=true
Troubleshooting guide: https://github.com/facebook/docusaurus/discussions/10580
- "/petstore_versioned/1.0.0/swagger-petstore-yaml":
- [HTML minifier diagnostic - error] No "p" element in scope but a "p" end tag seen - {"primary_spans":[{"end":21328,"start":21324}],"span_labels":[]}
- [HTML minifier diagnostic - error] Start tag "a" seen but an element of the same type was already open - {"primary_spans":[{"end":22536,"start":22459}],"span_labels":[]}
- [HTML minifier diagnostic - error] End tag "a" violates nesting rules - …
```

Address HTML minifier warnings caused by malformed MDX and HTML

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Authorization/index.tsx

Reintroduces password type to API key/token input fields. Although credentials will still be plain text in code snippets, we could at least mask them in the form input.
Could be helpful to mask API key/token or passwords when performing a live demo or screen recording. Next step is to find a viable approach to mask or obfuscate them in code snippets without breaking the underlying request.
Tested locally in dev. See deploy preview for production test.

Reintroduce password type to auth inputs

---

demo/examples/tests/discriminator.yaml
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx

See #1026 for background.
OpenAPI spec allows for defining discriminator schemas with no shared/parent properties. This PR adds support for this pattern by merging the discriminator property from mapped schemas into the parent.

Support discriminator with no parent/shared properties

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/buildPostmanRequest.ts

Follow up to #1039 with the goal of masking credentials in generated code snippets. The expected behavior is that any credentials included in code snippets will be replaced with placeholders, e.g. `<api_key>`, matching the key name of the credential property. Meanwhile, credentials passed to `makeRequest` will still be represented by the actual values.
Follows best practice of hiding credentials from UI to improve privacy and security. Additionally, anyone creating screenshots or demo videos will not need to worry about credentials leaking or having to blur or mask them before publishing/sharing.
Tested locally in dev

Hide credentials from generated code snippets

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx

Continuation of #1050 and #1039. Adds support for parsing auth placeholders when auth options are combined or required in pairs, e.g. id and key.
Ensures full coverage.
Tested with IoT API spec.

Handle case where auth options are combined

---

demo/package.json
demo/src/components/BrowserWindow/index.tsx
package.json
packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/LiveEditor/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ParamsDetails/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/RequestSchema/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ResponseSchema/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.tsx
yarn.lock

Upgrades demo and supporting packages to support Docusaurus 3.7.0. Changes should be backward compatible with previous supported releases.

Upgrade demo and packages to support 3.7.0

---

packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts

Addresses a bug that resulted in request body arrays rendering inside nested brackets. This change uses the `normalizeArray` utility to prevent this from happening.
Encountered this bug while testing the API Intercept async scan endpoint.
Tested using the API Intercept spec.

normalize body array instead of returning literal

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/LiveEditor/index.tsx

The LiveEditor was not recognizing examples when validating the `required` prop. This change extends the required validation to also check for the existence of a default code snippet. If a default code snippet exists users should no longer see the "This field is required" error. Previously, to get around this, users would need to "dirty" the `LiveEditor` form by making a small change. This fix will correct it so users can simply select an example and hit send without having to edit.
Improves user experience.
Tested using API Intercept spec
see deploy preview

Allow default body to satisfy required

---

demo/examples/petstore-3.1.yaml
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.tsx

See #1052 for background. 
Ultimately this plugin aims to provide as much support coverage as possible for OpenAPI 3.1, including null types.
Example added to OpenAPI 3.1 Petstore API.

Add support for json schema null type

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ParamOptions/ParamFormItems/ParamArrayFormItem.tsx

Addresses an issue that caused API requests to be inadvertently submitted while adding params array items to the request.
API requests should only be sent when users click the "Send API Request" button.
Tested using API Intercept spec
n/a

Prevent default behavior when adding params items 

---

packages/docusaurus-plugin-openapi-docs/package.json

Addresses issue described in #1072 
Missing peer dependency can block installation of plugin using `npm`.
Please note that workaround is possible using explicit `overrides` or `--force` option.
Tested using fresh docusaurus installation.

Add react 19 to plugin peer dependencies

---

demo/examples/tests/paramSerialization.yaml
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ParamOptions/ParamFormItems/ParamArrayFormItem.tsx
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/buildPostmanRequest.ts

This PR consists of adding support for `explode` and correct example generation for array query parameters.
See #1024 for context
Tested with OpenAPI example spec provided in #1024.

Expand support for parameter serialization

---

packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
yarn.lock

Node.js core modules are imported in client(browser) side. And the previsous code use node polyfill, however this would brings more issue:
1. `node:buffer`, `node:zlib`... where `node:` as prefix would still break the webpack bundler because `node-polyfill-webpack-plugin` didn't handle it correctly
2. node polyfill packages are mostly too outdated (many years no updates)
3. indirectly import `Buffer` could leads unexpected behavior
This PR remove node.js dependency, instead now uses pika and web api directly to reduce the bundle hack, bundle size and more explicit imports
For more context, docusaurus will raise error if use [nolyfill](https://github.com/SukkaW/nolyfill/pull/117)
Try this in demo and everything works
- New feature …

fix: remove node.js dependency in browser

---

packages/docusaurus-plugin-openapi-docs/src/markdown/schema.test.ts
packages/docusaurus-plugin-openapi-docs/src/markdown/schema.ts
packages/docusaurus-theme-openapi-docs/src/markdown/schema.ts

The check for maximum and minimum values missed the zero value, which is a falsy, so it was not rendered.
I’m using this addon for my project, but it doesn’t render the minimum/maximum value. [#754](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/754) was supposed to fix the issue, but it still persists, so I decided to resolve it myself.
- Added more unit tests to cover all new cases and ensure both new and existing tests pass.
- Tested in the demo, and everything is working fine.

fix: Zero values for minimum or maximum were not rendered

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

When building pages, the `downloadUrl` configuration property was previously only available to 'info' pages. It is now available to all types of pages.
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1093
I want to add a "download schema" option to individual API endpoint pages. It is currently not possible, as the config property is only provided to info pages.

downloadUrl option is now available to all API entities, previously only "info" pages

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

This PR addresses an issue in the event that an OpenAPI spec provides an empty request body, which causes the following error when running the `yarn gen-api` command: 
```
Loading of api failed for "/Users/blinda/Desktop/projects/docusaurus-openapi-docs/demo/examples/odinconnector.json"
[ERROR] TypeError: Cannot read properties of undefined (reading 'endsWith')
at createItems (/Users/blinda/Desktop/projects/docusaurus-openapi-docs/packages/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:155:41)
at processOpenapiFile (/Users/blinda/Desktop/projects/docusaurus-openapi-docs/packages/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:514:19)
at async /Users/blinda/Desktop/projects/docusaurus-openapi-docs/packages/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:468:35
at async …
```

[Bug Fix]: Cannot read properties of undefined (reading 'endsWith')

---

packages/docusaurus-theme-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/src/index.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Response/index.tsx
yarn.lock

See #1096 for background
> Note: we should probably work toward removing the `demo` app from the workspace to avoid dependency overlaps/conflicts. In this case, the `demo` app is relying on hoisted modules which creates a blind spot for identifying missing modules.

Remove URL plugin and fallback from webpack config

---

packages/docusaurus-theme-openapi-docs/src/theme-classic.d.ts
packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.tsx

This PR addresses the following issue for page crashes due to non-rendering `TabItem` components: 
See https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1086 for context. 
Tested with example spec provided in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1086 and navigating to `/get-series-list` path.

[Bug Fix] Render fragment for empty Discriminator Tabs children

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Body/index.tsx

When providing examples of `application/json` request body content, docusaurus-theme-openapi-docs will double escape the content for display and for use in code samples.
This pull request introduces changes to correctly render request body examples. This brings request body examples inline with response body examples which are already rendered correctly.
Minimal example
```yaml
openapi: 3.0.3
info:
title: Minimal Example
version: 1.0.0
servers:
- url: http://example.com
paths:
/demo:
post:
summary: Demo Endpoint
description: Demo incorrect request body rendering
requestBody:  
content:
application/json:
schema: 
type: object
properties:
test:
type: string
example: alpha
examples:
bravo:
summary: Bravo
value: |
{
"test": "bravo"
}
responses:
'200':
description: OK
content: …
```

Don't double encode application/json requestBody examples

---

CHANGELOG.md
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

See `CHANGELOG.md` for details

Prepare release v4.3.6

---

packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.tsx

This PR addresses a regression bug introduced in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/1099 which caused Discriminator Tabs to not render. The bug was caused by an invalid check against empty Discriminator `props` children.
See https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1106 for context.
Tested with example spec in [original issue](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1086) and navigating to `get-series-list`, as well as ensuring that Discriminator tabs are still rendering as expected under our available [Discriminator test examples](http://localhost:3002/tests/discriminator-variations-api).

[Bug Fix] Properly handle empty Discriminator Tab children

---

demo/docusaurus.config.ts
demo/examples/httpbin.yaml
demo/sidebars.ts

Adds the HTTPBin spec to provide a more interactive experience for evaluating API Explorer across different operations.
> Note: the original v2 spec was upgraded and heavily cleaned up using gpt-4o

Add httpbin.org spec to examples

---

.github/workflows/build-perf.yml
.github/workflows/canary-beta-release.yml
.github/workflows/canary-release.yml
.github/workflows/codeql-analysis.yml
.github/workflows/combine-dependabot-prs.yml
.github/workflows/deploy-live.yml
.github/workflows/deploy-preview.yml
.github/workflows/pr-title-check.yaml
.github/workflows/release-beta.yaml
.github/workflows/release.yaml
.github/workflows/validate.yaml

GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Pin GitHub Actions

---

demo/examples/tests/discriminator.yaml
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx

This PR addresses an issue where the OpenAPI spec defines a discriminator with a subschema that only inherits all fields from the parent (using allOf) and does not define any new properties. Previously, this pattern would cause a runtime error in the Docusaurus OpenAPI plugin due to an attempt to access properties of an undefined object.
See #1132 for more background.
OpenAPI allows for discriminator mappings where a child schema inherits all properties from its parent via allOf and does not introduce any new properties. This is a valid and common pattern for modeling inheritance. Prior to this fix, such schemas would cause the documentation build or runtime to fail with a TypeError. This PR adds a safeguard to ensure the code handles these cases gracefully, allowing the documentation to …

fix: handle discriminator subschemas that only inherit via allOf without own properties

---

packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx

Addresses issues described in https://github.com/PaloAltoNetworks/pan.dev/issues/891
- Proper handling of json-schema style enums 
- Address a regression bug introduced in #1009 
Tested with https://github.com/PaloAltoNetworks/pan.dev/blob/master/openapi-specs/scm/config/ngfw/security/security-services.yaml
Visual inspection of demo tests
n/a

Bug fixes for enums with no type and anyof/oneof schemas

---

packages/docusaurus-plugin-openapi-docs/src/index.ts

A regression bug was introduced in #1122 that resulted in build errors in cases where info pages were not used as `categoryLinkSource`.
```
Error: /access/api/insights/palo-alto-networks-3-0-apis/ is not associated with a category. useCurrentSidebarCategory() should only be used on category index pages.
```
This PR adds conditions back to ensure the info template is only applied when either:
* `categoryLinkSource` is set to "info" or
* A user defined `infoTemplate` is provided
The info template should only be applied in the cases mentioned above, otherwise fall back to just rendering the info page using the standard `view` template.

Conditionally apply info template

---

CHANGELOG.md
README.md
demo/docs/intro.mdx
demo/package.json
lerna.json
packages/docusaurus-plugin-openapi-docs/README.md
packages/docusaurus-plugin-openapi-docs/package.json
packages/docusaurus-theme-openapi-docs/package.json

Prepare release v4.4.0

---

demo/examples/tests/const.yaml
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx
packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.tsx

Support `const` as described in OAS 3.1.1.
Resolves: #1142
`const` allows you to declare a constant value.
It also helps compose annotated enumerations, as an improvement to the original `enum`.
REL: https://swagger.io/specification/#annotated-enumerations
I added a test schema (as seen in PR), and I ran it locally. I did not see any unit/integration test patterns in the repository.

feat: support const for OAS 3.1.1

---

packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/buildPostmanRequest.ts

This PR consists of added support for allowing Security Schemes with the type of `apiKey` to be used for the following parameter types: 
- `in: query`
- `in: cookie`
Although the original issue proposes that the value should be shown in the UI, we will continue to mask credentials to align with best security practices - while still allowing the user to make the underlying request within the Request Demo Panel.
See https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1150 for context.
Tested with the following spec and ensured that request can be made from Request Demo Panel: 
```
openapi: 3.0.3
info:
title: Test API key in Header
version: 1.0.0
servers:
- url: https://httpbingo.org
tags:
- name: Test
paths:
/get:
get:
operationId: getTest
tags:
- Test
summary: Test the …
```

[UI] Add support for apiKey in query and cookie param

---

demo/examples/tests/allOf.yaml
demo/examples/tests/anyOf.yaml
demo/examples/tests/oneOf.yaml
packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts
packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts
packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx

Ensure correct display when using properties along with allOf, anyOf, and oneOf in array child elements.
There's an issue where an object defined with properties combined with allOf, anyOf, and oneOf in array child elements doesn't display correctly. This addresses that problem.
For details, please refer to Issue https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/1153.
Added and verified new cases for allOf, anyOf, and oneOf in the demo tests.
- allOf with Properties in Array Item
- anyOf with Properties in Array Item
- oneOf with Properties in Array Item
Confirmed that examples are displayed correctly.
- allOf with Properties in Array Item
- anyOf with Properties in Array Item
- oneOf with Properties in Array Item
Fixed …

Support allOf, anyOf, and oneOf schemas with properties in array item

---

.github/workflows/deploy-preview.yml

Limit the permissions available to `visual_diff` from `.github/workflows/deploy-preview.yml`
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/actions/runs/16152037957 seems to have worked as expected.
N/A

Update GitHub Actions

---

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/buildPostmanRequest.ts

This pull request addresses issue #1199 (URIError when entering percent sign (%) in API Explorer) by wrapping the `decodeURI` call in a `try-catch` block to gracefully handle malformed input.
Without this fix, the API Explorer crashes when a percent sign (%) is entered in query or path parameters. Additionally, entering the string `"null"` in path parameters also causes a crash. This update ensures the application remains stable when encountering such inputs.
- Entering `%` in query or path parameters previously caused a crash — now handled safely.
- Entering `"null"` in path parameters previously caused a crash — now handled safely.
- ✅ Bug fix (non-breaking change which fixes an issue)

fix: properly encode parameters

---

demo/docs/customization/doccard.mdx

- add instructions for swizzling DocCard to render Markdown
Addresses #1159

docs: explain swizzling DocCard

---

packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts

Check for validation results that will result in an error and reject with that error.
Also, add additional safety around the `conversionResult` handling to avoid generic errors on failure.
When a spec is provided that was missing required fields (`title`, `version`) in the `info` section, the build process would fail with a generic `TypeError` due to `conversionResult` not existing.
Only locally in the compiled `node_modules` environment.

Improve error handling when spec isn't valid
