packages/docusaurus-plugin-openapi/src/markdown/createStatusCodes.ts
=> Use alert--info for 1xx status codes

CHANGELOG.md, cypress/integration/test.spec.ts, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-openapi/src/markdown/createParamsDetails.ts, packages/docusaurus-plugin-openapi/src/markdown/createRequestBodyDetails.ts, packages/docusaurus-plugin-openapi/src/markdown/createSchemaDetails.ts, packages/docusaurus-plugin-openapi/src/markdown/createStatusCodes.ts, packages/docusaurus-plugin-openapi/src/markdown/index.ts, packages/docusaurus-plugin-openapi/src/openapi/openapi.ts, packages/docusaurus-plugin-openapi/src/sidebars/index.ts, packages/docusaurus-plugin-openapi/src/sidebars/sidebars.test.ts, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-template-openapi/template.json, packages/docusaurus-theme-openapi/package.json, packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/MethodEndpoint/index.tsx, packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/ParamOptions/index.tsx, packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx, packages/docusaurus-theme-openapi/src/theme/ApiItem/styles.module.css, packages/docusaurus-theme-openapi/src/theme/Tabs/index.js, packages/docusaurus-theme-openapi/src/theme/Tabs/styles.module.css, yarn.lock
* Disable schemaFaker
* Cleanup UI
* Upgrade `openapi-to-postmanv2`
* Use Tabs for status codes
* Fix infinite render in ParamOptions
* Fix code blocks width
* Switch to details component for schemas
=> Prepping for new release

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json
=> Prepare release v17.0.1

packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-template-openapi/template/docusaurus.config.js
Manually bumped the following packages to v17.0.3:
* `create-docusaurus-openapi`
* `docusaurus-plugin-proxy`
* `docusaurus-template-openapi`
Also manually published these packages to npm.
=> Manually bump to 17.0.3

package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-openapi/patches/postman-collection+4.1.1.patch, packages/docusaurus-theme-openapi/package.json, packages/docusaurus-theme-openapi/patches/postman-code-generators++postman-collection+3.6.8.patch, packages/docusaurus-theme-openapi/patches/postman-code-generators+1.1.5.patch
Currently, `patch-package` only runs at the lerna workspace root level and not for individual packages. This change introduces patches directory and `postinstall` scripts to `docusaurus-plugin-openapi` and `docusaurus-theme-openapi` so that patches are applied when these packages are installed individually from npm registry. Only the patches applicable to each package are included.
If this works, additional efforts will be made to inform users of this behavior and instructions on how to disable patching during installation, i.e. `yarn install --ignore-scripts`.
Patches greatly reduce the overall bundle size.
- Breaking change (fix or feature that would cause existing …
=> Add patch-package to standalone packages

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json
=> Prepare release v17.0.5

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json, yarn.lock
=> Prepare release v17.0.6

demo/src/css/custom.css
Removing custom styles from demo to always work from a clean slate.
=> Remove custom styles from demo

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json
=> Prepare release v17.0.7

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json
=> Prepare release v17.0.8

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-plugin-proxy/package.json, packages/docusaurus-preset-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json
See `CHANGELOG.md` for details.
=> Prepare release v17.0.9

packages/docusaurus-plugin-openapi/src/index.ts
Fixes broken conditional statement in `docusaurus-plugin-openapi` default mustache template that prevented `api` frontmatter from getting written to MDX files.
Issue prevents `ApiDemoPanel` from displaying.
=> [Bug] Fix mustache template

packages/docusaurus-theme-openapi/src/theme/ApiItem/index.tsx
Wrap DocItem for ApiItem
By wrapping, we are able to get the latest DocItem without manually upgrading. 
I built it. Looked at it.
=> wrap DocItem for ApiItem

CHANGELOG.md, demo/package.json, lerna.json, packages/create-docusaurus-openapi/package.json, packages/docusaurus-plugin-openapi/package.json, packages/docusaurus-template-openapi/package.json, packages/docusaurus-theme-openapi/package.json
This release introduces two new Docusaurus CLI commands for managing OpenAPI docs: `gen-api-docs` and `clean-api-docs`. In addition to this, all plugin options can now be easily managed within a single plugin instance by containing them in a single `config` option. Additional support for generating a sidebar slice can be achieved by specifying `sidebarOptions` within a plugin option. Please refer to changelog for other minor enhancements and bug fixes associated with this release. 
```bash
yarn docusaurus gen-api-docs all
```
```bash
yarn docusaurus clean-api-docs all
```
Example `docusaurus.config.js`:
```
plugins: [
[
"@paloaltonetworks/docusaurus-plugin-openapi",
{
id: "here",
config: {
petstore: {
specPath: "examples/petstore.yaml",
outputDir: "api/petstore",
sidebarOptions: { …
```
=> Prepare release v18.0.0-beta.1

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SUPPORT.md
Updates to the following documentation: 
- `CONTRIBUTING.md`
- `SUPPORT.md`
- `CODE_OF_CONDUCT.md`
=> Update CONTRIBUTING, SUPPORT, and CODE_OF_CONDUCT

README.md, packages/docusaurus-plugin-openapi/README.md
- Update `docusaurus-plugin-openapi` README with usage
- Update `docusaurus-openapi-docs` README with usage
=> Update README with usage

README.md, packages/docusaurus-plugin-openapi-docs/README.md
=> [Spring Cleaning] Update READMEs

README.md, packages/docusaurus-plugin-openapi-docs/README.md
- Update `docusaurus-openapi-docs` and `docusaurus-plugin-openapi-docs` README with a table of configuration options.
=> [Spring Cleaning] Update READMES with Configuration Options table

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
See `CHANGELOG.md` for details.
=> Prepare release v1.0.0

packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
Minor tweaks to plugin and theme package.json.
* Added keywords to improve indexing on npmjs
* Updated git URLs due to recent renaming
=> [Packaging] Add package.json keywords and update git URL

README.md, demo/package.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
Pins packages and demo to Docusaurus v2.0.0-beta.18. Will continue to monitor status of latest release (2.0.0-beta.19) and will upgrade when viable upgrade path exists.
=> [Fix Breaking Change] Pin to docusaurus 2.0.0-beta.18

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.0.1

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.0.2

demo/src/css/custom.css, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/MethodEndpoint/index.tsx
Adds handler for `head` HTTP method and appropriate colored badge. 
```javascript
function colorForMethod(method: string) {
switch (method.toLowerCase()) {
case "get":
return "primary";
case "post":
return "success";
case "delete":
return "danger";
case "put":
return "info";
case "patch":
return "warning";
case "head":
return "secondary";
default:
return undefined;
}
}
```
Consistency and readability.
=> [Polish] Add support for head method and badge

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
See `CHANGELOG.md` for details.
=> Prepare release v1.0.3

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.0.4

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.0.6

packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndBundleSpec.ts
=> Add await to resolveJsonRefs

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.0

demo/package.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
Upgrade to latest Docusaurus `2.0.0-rc.1`
Remain aligned and provide compatibility with the latest Docusaurus version.
- Tested locally (dev and prod) to ensure there weren't any breaking changes and all functionality throughout the site remained intact
- Tested the flow of cleaning and regenerating OpenAPI docs
=> [Upgrade] Docusaurus 2.0.0-rc.1 support

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.1

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.2

README.md, demo/docs/intro.mdx, demo/package.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json, yarn.lock
Upgrades Docusaurus to v2.0.1.
=> Upgrade to Docusaurus v2.0.1

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.3

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.4

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.5

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.6

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.7

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.8

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.9

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.10

.github/workflows/combine-dependabot-prs.yml
Adds workflow for auto-merging dependabot PRs. Works by finding all open dependabot PRs and compiling their diffs into a single PR. Once that PR is merged all the PRs are closed, including the originals.
Improve overall security of project.
=> Add combine dependabot workflow

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
See #245 for background.
Fixes an issue that prevented required object properties from being labeled as required.
=> [Bug] Fix logic that determines if an object property is required

package.json, yarn.lock
Upgrades lerna to 5.5.0
Allow for upgrading vulnerable dependencies.
=> Upgrade lerna to 5.5.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.11

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.1.12

packages/docusaurus-theme-openapi-docs/package.json, yarn.lock
Upgrades @paloaltonetworks/postman-code-generators to help patch vulnerable dependencies.
=> Upgrade postman-code-generators

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.2.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.2.1

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FloatingButton/styles.module.css, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/styles.module.css, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/styles.module.css, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
Moving server/Base URL select to inside Request card.
Base URL selection fits naturally inside the request area.
=> [Experimental] Move server input to request card

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.2.2

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.3.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.3.1

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.3.2

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.4.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.4.1

packages/docusaurus-plugin-openapi-docs/src/index.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
See #324 for background and test results.
> Regression bug introduced by #320
=> [Bug] Improve support for multiline descriptions in frontmatter

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.4.2

demo/docusaurus.config.js
This PR consists of implementing Algolia DocSearch with the necessary configurations.
In order to allow users to search and navigate quickly throughout the site.
Tested by searching for terms related to docs that are currently on the site and was able to successfully navigate to desired page.
=> [Enhancement]: Implement Algolia DocSearch

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.4.4

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.4.5

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/makeRequest.ts
Fix `Body` import in `makeRequest.ts` to allow for swizzling.
See #246
=> [Bug] Import Body from @theme in makeRequest

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.4.6

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
Emergency release to fix breaking change introduced in v1.4.6
=> Prepare release v1.4.7

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.5.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.5.1

README.md
This updates the link to docusaurus-openapi, so that it points to the project indicated by the link text.
- Minor change to the README
=> Update a link in the credits

demo/docusaurus.config.js, demo/examples/petstore.yaml, demo/sidebars.js
=> Cleanup API doc demos

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.5.2

demo/docs/customization/languagetabs.md, demo/docusaurus.config.js, packages/docusaurus-theme-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/styles.css, yarn.lock
Added support for java OkHttp variant. Will explore how to support both `OkHttp` and `Unirest` variants in future release.
Addresses request mentioned in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/discussions/394
=> Add support for java and expand language variants

packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
Cherry-picked from #247
#247 only fixed this issue in rendering request schema. A similar problem also exists in rendering response body schema. 
- Bug fix
=> fix: fix logic that determines if an object property is required in response

demo/docusaurus.config.js, packages/docusaurus-plugin-openapi-docs/src/index.ts, packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
=> Remove trailing slash in outputDir option if present

packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts, packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
* Point to test spec
* Add utility for casting to string
* More explicitly check for undefined and add code comments to toString()
* Revert back to demo petstore spec
=> Improve handling of non-string default values (#436)

demo/docusaurus.config.js, packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
Addresses issue #403 
> Ignore the failed Cypress test
=> [bug] Use toString() utility to always convert example to string

demo/docusaurus.config.js, demo/src/css/custom.css, demo/src/utils/prismDark.mjs, demo/src/utils/prismLight.mjs
Applying docusaurus.io styles for more honest reflection of what default UI/UX will resemble OOTB. This is also in preparation for new v2.0.0 UI/UX redesign to ensure we start with a clean slate.
=> Apply docusaurus.io styles to demo

packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts
Addresses issue reported in #453
=> Add code, thead and tbody to greaterThan regex

packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css
Remove CSS test styles introduced in #461 
=> [UI] Remove code tab test styling

packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts, packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts
=> Eval guard value as double not

.github/workflows/pr-title-check.yaml, .github/workflows/release.yaml
=> Add v2.0.0 branch to release workflows

.github/workflows/release-beta.yaml, scripts/publish-beta.ts
Preparation for supporting v2.0.0 beta releases
=> Split beta release into separate script/workflow

demo/docusaurus.config.js, packages/docusaurus-theme-openapi-docs/src/theme-openapi.d.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/makeRequest.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/slice.ts, packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Refactor of #308 with support for v2.3.0
Also adds response headers and organizes code and headers into tabs.
=> [UI Enhancement] Refactor include status code in response

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
=> Additional BEM/CSS cleanup

CHANGELOG.md, demo/package.json, lerna.json, package.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json, scripts/changelog-beta.ts
=> Prepare release v2.0.0-beta.1

CHANGELOG.md, README.md, demo/docs/customization/languagetabs.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v1.7.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.0.0-beta.2

packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/MethodEndpoint/index.tsx
Added classes to the `MethodEndpoint` component to improve Algolia search for endpoint paths. 
The following selectors have been added: 
1. `openapi-method-endpoint` - class for `pre` wrapper
2. `openapi-method-endpoint__path` - class for the endpoint path
Will be tested via Algolia search
=> Improve Algolia search for method endpoint paths

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js, packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.js, packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/styles.module.css, packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/index.js, packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js, packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js, packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js, packages/docusaurus-theme-openapi-docs/src/theme/styles.css
=> [Bug] Add handler for oneOf properties, fix nested <li> and and avoid duplicate properties in createAnyOneOf 

packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/_Request.scss, packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/_ParamsItem.scss, packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/_SchemaItem.scss
Minor CSS fixes to cleanup schema item `name` and API Explorer panel request caret alignment.
=> [UI] Cleanup schema item and explorer panel caret alignment

packages/docusaurus-plugin-openapi-docs/src/markdown/createDeprecationNotice.ts
Updates the deprecation message as follows:
Before: "This endpoint has been deprecated and may be removed in future versions of the API."
After: "This endpoint has been deprecated and may be replaced or removed in future versions of the API."
Leaves room for endpoints to be replaced.
Tested with Compliance Posture API spec
=> update deprecation message

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/MethodEndpoint/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/index.tsx
=> Improve webhook layout

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.1

packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/makeRequest.ts
Ports targeted commits from v2 branch
=> Port v2 changes/fixes into v3

CHANGELOG.md, demo/docusaurus.config.js, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.2

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.0.1

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.0.2

.vscode/settings.json, demo/package.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json, yarn.lock
Canary release workflow failed with the following:
```
lerna info auto-confirmed 
- demo: 3.0.0-beta.2 => 0.0.0-beta.692 (private)
- docusaurus-plugin-openapi-docs: 3.0.0-beta.2 => 0.0.0-beta.692
- docusaurus-theme-openapi-docs: 3.0.0-beta.2 => 0.0.0-beta.692
lerna info execute Skipping git push
lerna info execute Skipping releases
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/home/runner/work/docusaurus-openapi-docs/docusaurus-openapi-docs/node_modules/@lerna/version/lib/git-add.js:32:49)
lerna ERR!     at gitAdd (/home/runner/work/docusaurus-openapi-docs/docusaurus-openapi-docs/node_modules/@lerna/version/lib/git-add.js:51:5)
lerna ERR!     at /home/runner/work/docusaurus-openapi-docs/docusaurus-openapi-docs/node_modules/@ …
```
=> Install eslint prettier plugin

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.3

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.4

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.0.3

CHANGELOG.md, demo/docs/customization/languagetabs.mdx, demo/package.json, lerna.json, package.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts, packages/docusaurus-theme-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/src/theme-openapi.d.ts, packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Body/index.tsx, packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/languages.json, packages/docusaurus-theme-openapi-docs/src/theme/Markdown/index.js, yarn.lock
=> Prepare release v3.0.0-beta.5

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.0.4

README.md, demo/docs/intro.mdx, packages/docusaurus-plugin-openapi-docs/README.md
Update compatibility matrix to reflect current support
=> update compatibility matrix

packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createCallbacks.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createContactInfo.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createLicense.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createLogo.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createParamsDetails.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestBodyDetails.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts, packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/utils/services/OpenAPIParser.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/utils/utils/openapi.ts, scripts/changelog-beta.ts, scripts/changelog.ts, scripts/check-pr-title.ts, scripts/publish-beta.ts, scripts/publish.ts, yarn.lock
=> Upgrade dependencies

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.6

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.1.0

packages/docusaurus-plugin-openapi-docs/package.json, yarn.lock
Upgrade parsers to improve OpenAPI 3.1 support
=> Upgrade OpenAPI parsers

packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
=> cleanup console log

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.1.1

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.7

packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap, packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
Adds qualifier to primitive schema items.
Addresses #747 
Tested using the OpenAPI snippet provided in #747
=> Ensure qualifiers are rendered for polymorphic/primitive properties

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.1.2

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.1.3

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.tsx
=> Prepare release v3.0.0-beta.9

packages/docusaurus-plugin-openapi-docs/src/markdown/createVersionBadge.ts
=> Use inline to remove p tag

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.0-beta.10

demo/package.json, yarn.lock
Upgrades v3 demo to latest docusaurus
=> Upgrade demo to docusaurus 3.3.2

demo/package.json, yarn.lock
upgrade demo to latest docusaurus
=> upgrade to docusaurus 3.4.0

packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
=> Version dropdown styles

packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
=> fix typo in attribute

demo/docusaurus.config.ts, demo/static/petstore.yaml, packages/docusaurus-plugin-openapi-docs/src/index.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
=> Support absolute or relative downloadUrl

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
Addresses regression bug described in #870
=> Fall back to languageSet if no languageTabs provided

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-preview.yml, .github/workflows/pr-title-check.yaml, .github/workflows/release.yaml, .github/workflows/validate.yaml
Updates workflows to allow publishing v2.0.0 to npm
=> allow publishing for v2.0.0 branch

packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
* fall back to languageSet is no languageTabs provided
* switch to nullish operator
=> Fall back to languageSet if no languageTabs provided (#871)

CHANGELOG.md, README.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.2.1

demo/examples/petstore.yaml, packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap, packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
=> Add object primitive support to createAnyOneOf

packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts, packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts
=> Statically set "generated" date and date-time example values

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v3.0.2

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
See changelog
> Note that this release breaks backward compatibility with v3.0.x
=> Prepare release v4.0.0

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v2.2.3

CHANGELOG.md, README.md, demo/docs/intro.mdx, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v4.0.1

packages/docusaurus-plugin-openapi-docs/src/markdown/createDeprecationNotice.ts
=> Fix deprecation notice

cypress/integration/__snapshots__/testSchemaSnapshots.spec.ts.snap, cypress/integration/testSchemaSnapshots.spec.ts, cypress/plugins/index.ts, cypress/support/cypress-plugin-snapshots.d.ts, package.json, yarn.lock
Uses snapshots to test/monitor changes to how schemas are rendered
=> refactor create schema tests to cypress

packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss
Small CSS change to fix vertical alignment of response schema details marker
=> Fix response schema details marker alignment

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
See `CHANGELOG.md` for details.
=> Prepare release v4.3.0

CHANGELOG.md, README.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/README.md, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v4.3.2

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v4.3.3

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v4.3.4

packages/docusaurus-theme-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/src/index.ts, yarn.lock
=> add missing buffer and url modules

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v4.3.5

CHANGELOG.md, demo/package.json, lerna.json, packages/docusaurus-plugin-openapi-docs/package.json, packages/docusaurus-theme-openapi-docs/package.json
=> Prepare release v4.3.7

.github/workflows/build-perf.yml, .github/workflows/deploy-preview.yml, .github/workflows/release-beta.yaml, .github/workflows/release.yaml, .github/workflows/validate.yaml
Additional hardening measures for GitHub Actions
=> Additional hardening measures for GitHub Actions workflows
